<include file="Include:header" />
<style type="text/css">
html {
	background: none;
}

.tbb {
	border-collapse: collapse;
}

.gray {
	font-weight: bold;
	background: #f7f7f7;
}

.tbb td {
	padding: 5px;
	font-size: 12px;
	border: 1px solid #999;
}

.tbb th {
	padding: 5px;
	font-size: 13px;
	background: #efefef;
	border: 1px solid #999;
}

.input_text {
	width: 95%;
}
</style>
<script src="__PUBLIC__/js/initcity.js" type="text/javascript"></script>
<script language="javascript">
$(document).ready(function(){
	$('.bgloader').fadeOut(500);
	pc_init();
	<?php if(ACTION_NAME == "managerEdit") :?>
	$("#id").attr("value",'<?=$rs['id']?>');
	$("#name").attr("value",'<?=$rs['u_name']?>');
	$("#company").attr("value",'<?=$rs['u_company']?>');
	$("#shengfen").html('<?=$rs['u_province']?>');
	$("#chengshi").html('<?=$rs['u_city']?>');
	$("#tel").attr("value",'<?=$rs['u_tel']?>');
	$("#manager").attr("value",'<?=$rs['u_manager']?>');
	$("#phone").attr("value",'<?=$rs['u_phone']?>');
	$("#addr").attr("value",'<?=$rs['u_address']?>');
	$("#email").attr("value",'<?=$rs['u_email']?>');
	$("#u_group").attr("value",'<?=$rs['u_group']?>');
	$("#province").attr("disabled",true);
	$("#city").attr("disabled",true);
	$("#isedit").change(function() {
		if($(this)[0].checked == true){
			$("#province").attr("disabled",false);
			$("#city").attr("disabled",false);
		}else{
			$("#province").attr("disabled",true);
			$("#city").attr("disabled",true);
		}
	}); 
	<?php endif;?>
});
function submitForm(w){
	$.post(
			"<?=U("Manager/".ACTION_NAME)?>",
			$("#form").formSerialize(),
			function(data){
				if(data.status=="1"){
					Maya.Msg({
						type : "success",
						msg : "操作成功",
						call : function(){
							w.close();
							freshIframe();
						}	
					});	
				}else{
					Maya.Msg(data.info);	
				}
			},
			"json"
		);
}
</script>
<body>
	<div class="content">
		<div class="bgloader"></div>
		<form id="form" name="form">
		<input id="id" name="id" type="hidden" value="<?=$_GET['id']?>" />
			<table border="0" cellspacing="0" cellpadding="0"
				style="width: 400px; margin: 20px auto;" class="tbb">
				<tr>
					<td class="gray" height="30" align="right"><span class="mustIn">*</span>&nbsp;用户名：</td>
					<td><input id="name" name="name" type="text" class="input_text"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right"><span class="mustIn">*</span>&nbsp;密码：</td>
					<td><input id="pwd" name="pwd" type="text" class="input_text"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right"><span class="mustIn">*</span>&nbsp;公司名称：</td>
					<td><input id="company" name="company" type="text"
						class="input_text" style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">所在地区：</td>
					<?php if(ACTION_NAME == "managerEdit") :?>
					<td>&nbsp;&nbsp;<label id="shengfen"></label><label id="chengshi"></label>&nbsp;&nbsp;&nbsp;
						<label><input type="checkbox" id="isedit" name="isedit" />修改</label>
						<select id="province" name="province"></select><select id="city"
						name="city"></select>
					</td>
					<?php else:?>
					<td>
						<select id="province" name="province"></select>
						<select id="city" name="city"></select>
					</td>
					<?php endif;?>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">公司电话：</td>
					<td><input name="tel" type="text" class="input_text" id="tel"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right"><span class="mustIn">*</span>&nbsp;联系人：</td>
					<td><input name="manager" type="text" class="input_text"
						id="manager" style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">联系人电话：</td>
					<td><input name="phone" type="text" class="input_text" id="phone"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">公司地址：</td>
					<td><input name="addr" type="text" class="input_text" id="addr"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right"><span class="mustIn">*</span>&nbsp;常用邮箱：</td>
					<td><input name="email" type="text" class="input_text" id="email"
						style="width: 200px;" /></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">所在用户组：</td>
					<td><select id="u_group" name="u_group">
						<?php foreach($gArr as $row):?>
							<option value="<?=$row['id']?>"><?=$row['g_name']?></option>
						<?php endforeach;?>
					</select></td>
				</tr>
			</table>
	</form>
	</div>
</body>
</html>