<include file="Include:Header" />
<script src="__PUBLIC__/js/initcity.js" type="text/javascript"></script>
<script language="javascript">
$(function(){
	pc_init();
})
function submitForm(w){
	if($.trim($("#company").val())==""){
		Maya.Msg("请填写 <strong>公司名称</strong>");
		return false;	
	}
	if($.trim($("#manager").val())==""){
		Maya.Msg("请填写 <strong>联系人姓名</strong>");
		return false;	
	}
	if($.trim($("#name").val())==""){
		Maya.Msg("请填写 <strong>用户名</strong>");
		return false;	
	}
	if($.trim($("#pwd").val())=="" || $.trim($("#new_pwd").val())==""){
		Maya.Msg("请填写 <strong>密码</strong> 或 <strong>重复密码</strong>");
		return false;	
	}
	/*if(isNaN(the.QQ.value)){
		alert("你输入的QQ不是数字！");
		the.QQ.focus();
		return false;
	}*/
	Maya.Msg({
	    msg : "正在提交中，请稍后....",
	    sec : 1.5,
  	});
    $.post(
            "<?=U(MODULE_NAME.'/'.ACTION_NAME)?>",
            $("#form").formSerialize(),
            function(data){
                    if(data.data == "success"){
                            Maya.Msg({
                                    type : "success",
                                    msg : data.info,
                                    sec : 1.5,
                                    call : function(){
                                        w.close();
                                            //window.location="<?=U("Index/index")?>";
                                    }
                            });
                    }else{
                            Maya.Msg({
                                    type : "fail",
                                    msg : data.info
                            });
                    }
            },
            "json"
    );
	return false;
}
</script>
</head>
<body>
<div class="content">
	<!-- <input name="login_name" type="text" class="login_input"
				id="login_name" onfocus="if(this.value=='登录名'){this.value='';}"
				onblur="if(this.value==''){this.value='登录名';}" value="登录名" /> <input
				name="login_pwd" type="password" class="login_input" id="login_pwd"
				onfocus="if(this.value=='登录密码'){this.value='';}"
				onblur="if(this.value==''){this.value='登录密码登录密码登录密码登录密码';}"
				value="登录密码" /> <span class="login_btn" id="login_btn"></span> -->
	<form id="form" name="form">
		<div class="form_pad_10">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="75" height="30" align="right">用户名：</td>
					<td><input name="name" type="text" class="input_text" style="width:200px;"
						id="name" />&nbsp;<span class="mustIn">*</span>&nbsp;5-20位，字母数字下划线</td>
				</tr>
				<tr>
					<td height="15" align="right"></td>
					<td><span class="mustIn" style=" font-size:9px;">&nbsp;强烈建议使用QQ号码作为用户名</span></td>
				</tr>
				<tr>
					<td height="30" align="right">密 码：</td>
					<td><input name="pwd" type="password" class="input_text" style="width:200px;"
						id="pwd" />&nbsp;<span class="mustIn">*</span>&nbsp;5-20位，字母数字下划线</td>
				</tr>
				<tr>
					<td height="30" align="right">重复密码：</td>
					<td><input name="new_pwd" type="password" class="input_text" id="new_pwd" style="width:200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;重复输入上面的密码</td>
				</tr>
				<tr>
					<td height="30" align="right">公司名称：</td>
					<td><input id="company" name="company" type="text" class="input_text" style="width:200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;贵公司名称</td>
				</tr>
				<tr>
					<td height="30" align="right">所在地区：</td>
					<td><select id="province" name="province"></select><select id="city" name="city"></select></td>
				</tr>
				<tr>
					<td height="30" align="right">公司电话：</td>
					<td><input name="tel" type="text" class="input_text" id="tel" style="width:200px;" /></td>
				</tr>
				<tr>
					<td height="30" align="right">联系人：</td>
					<td><input name="manager" type="text" class="input_text" id="manager" style="width:200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;联系人姓名</td>
				</tr>
				<tr>
					<td height="30" align="right">联系人电话：</td>
					<td><input name="phone" type="text" class="input_text" id="phone" style="width:200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;联系人电话</td>
				</tr>
				<tr>
					<td height="30" align="right">公司地址：</td>
					<td><input name="addr" type="text" class="input_text" id="addr" style="width:200px;" /></td>
				</tr>
				<tr>
					<td height="30" align="right">常用邮箱：</td>
					<td><input name="email" type="text" class="input_text" id="email" style="width:200px;" /></td>
				</tr>
			</table>
		</div>
	</form>
</div>
</body>
</html>