<include file="Include:Header" />
<script language="javascript">
$(document).ready(function(){
});
function submitForm(w,type){
	$("#type").val(type);
	$.post(
			"<?=U(MODULE_NAME.'/'.ACTION_NAME)?>",
			$("#form").formSerialize(),
			function(data){
				if(data.data=="success"){
					Maya.Msg({
                        type : "success",
                        msg : data.info,
                        call : function(){
                        	w.close();
                        }
               		 });
				}else{
					Maya.Msg({
                        type : "fail",
                        msg : data.info
               		});	
				}
			},
			"json"
		);
	return false;
}
</script>
<div class="content">
	<form id="form" name="form">
		<input id="id" name="id" type="hidden" value="<?=$rs['id']?>" />
		<input id="type" name="type" type="hidden" />
		<div class="form_pad_10">
			<div align="center" style="font-size: 28px; padding: 10px;">
				<strong>会员充值信息</strong>
			</div>
			<div align="center" style="padding-bottom: 15px;">
				<strong>日期</strong>：
            <?=date('Y 年 m 月 d 日')?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>编号</strong>：<?='CM'.date('YmdHis')?></div>
			<table cellspacing="0" cellpadding="0" class="tb">
				<tr>
					<td width="60" align="right" style="height: 35px;"><b>会员名</b></td>
					<td width="200"><?=$rs['u_name']?></td>
					<td width="60" align="right"><b>公司名称</b></td>
					<td width="200"><?=$rs['u_company']?></td>
				</tr>
				<tr>
					<td align="right" style="height: 35px;"><b>汇款日期</b></td>
					<td><?=$rs['re_date_format']?></td>
					<td align="right"><b>充值金额</b></td>
					<td><?=$rs['re_money']?>&nbsp;元</td>
				</tr>
				<tr>
					<td align="right" style="height: 35px;"><b>账户</b></td>
					<td><?=$rs['re_bankInfo']?></td>
					<td align="right"><b>目标账户</b></td>
					<td><?=$rs['re_myBank']?></td>
				</tr>
				<tr>
					<td align="right" style="height: 35px;"><b>提交日期</b></td>
					<td><?=$rs['re_subDate_format']?></td>
					<td align="right"><b>余额</b></td>
					<td><?=$rs['re_overage']?></td>
				</tr>
				<tr>
					<td align="right" style="height: 35px;"><b>审核人</b></td>
					<td><?=$rs['sub_user']?></td>
					<td align="right"><b>状态</b></td>
					<td><?php
					if ($rs ['re_status'] == 0) {
						echo "<span style='color:#E4C600;'>审核中</span>";
					} else if ($rs ['re_status'] == 1) {
						echo "<span style='color:blue;'>成功</span>";
					} else {
						echo "<span style='color:red;'>失败</span>";
					}
					?></td>
				</tr>
				<tr>
					<td align="right" style="height: 45px;"><b>备注</b></td>
					<td colspan="3"><?=$rs['re_desc']?></td>
				</tr>
			</table>
		</div>
	</form>
</div>