<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	$('#btnedit').linkbutton('disable');
	$('#btndel').linkbutton('disable');	
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","订单列表","<?=U('InvoiceManager/getProduceLabelListJson')?>","#dbTool");
});
function filterData(){
	var uName = $('#uName').val();
	var dstart = $('#dstart').datebox('getValue');
	var dend   = $('#dend').datebox('getValue');
	var status = $('#status').val();
	$.post(
			"<?=U('InvoiceManager/getProduceLabelListJson')?>",
			{
				status:status,
				uName:uName,
				dstart:dstart,
				dend:dend,
				page:oPage.pageIndex,
				rows:oPage.pageSize
			},
			function(data){
					$('#tbl').datagrid('getPager').pagination({
						onSelectPage : function(pPageIndex, pPageSize) {
							//改变oPage的参数值，用于下次查询传给数据层查询指定页码的数据
							oPage.pageIndex = pPageIndex;
							oPage.pageSize = pPageSize;
							$.post(
									"<?=U('InvoiceManager/getProduceLabelListJson')?>",
									{
										status:status,
										uName:uName,
										dstart:dstart,
										dend:dend,
										page:oPage.pageIndex,
										rows:oPage.pageSize
									},
									function(data){
										$("#tbl").datagrid("loadData",data);
									},'json'
							);
							//异步获取数据到javascript对象，入参为查询条件和页码信息
							//var oData = getAjaxDate("orderManageBuz","qryWorkOrderPaged",queryCondition,oPage);
							//使用loadDate方法加载Dao层返回的数据
							//$('#tt').datagrid('loadData',{"total":oData.page.recordCount,"rows":oData.data});
							
						}
					});
					$("#tbl").datagrid("loadData",data);
			},
			"json"
		);
	return false;
}

function selectOrder(){
	var selected = $('#tbl').datagrid('getSelections');
	if(selected.length == 0){
		Maya.Msg("请选择订单【单击行即可】");
		return "";
	}
	if(selected.length > 1){
		Maya.Msg("未防止误操作，一次只可操作一笔订单。");
		return "";
	}
	return selected[0];
}

function getLabel(){
	var sel = selectOrder();
	var id = sel.id;
	if(sel == "")return;
	if(sel.hasWOrder == 0){
		createWorkerOrder(id,'add');
		return;
	}
	new Maya.Box({
		text : "加工单详细信息",
		url : "<?=U ( "InvoiceManager/getLabel" )?>/id/"+id,
		win : parent,
		width : 800,
		height : 220,
		btns : [
	    	{
				text : "    打印    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
				}	
			},{
				text : "    修改    ",
				onClick : function(w){
					createWorkerOrder(id,'edit');
					w.close();
				}	
			},
    		{
				text : "    确定    ",
				isCancel : true	
			}
		]
	});
}

function createWorkerOrder(id,type){
	if(id == 0){
		var sel = selectOrder();
		if(sel == "")return;
		id = sel.id;
	}
	new Maya.Box({
		text : type == "add" ? "生成加工单" : "加工单修改",
		url : "<?=U ( "InvoiceManager/createOrderWorkOrder" )?>/id/"+id+"/type/"+type,
		win : parent,
		width : 800,
		height : 220,
		btns : [
	    	{
				text : "    确定    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
				}	
			},
    		{
				text : "    取消    ",
				isCancel : true	
			}
		],
		onClose:function(){
			$("#tbl").datagrid("reload");
			setTimeout('getLabel()',1000);
		}
	});
}
function show(){
	var selected = selectOrder();
	if(selected == "")return;
	var id = selected.id;
	new Maya.Box({
		text : "订单详细信息",
		url : "<?=U ( "InvoiceManager/showOrder" )?>/id/"+id,
		win : parent,
		width : 700,
		height : 220,
		btns : [
    		{
				text : "    确定    ",
				isCancel : true	
			},{
				text : ' 详细信息(内部)',
				onClick : function(w){
					w.getIframe().showAll(w,selected.offer_id);
					// _self.close();
				}	
			}
		]
	});
}

function produced(){
	var selected = selectOrder();
	if(selected.o_status != "producing")return;
	var id = selected.id;
	var title = selected.p_name+"<br />订单号："+selected.o_number;
	new Maya.Box({
		text : "订单生产完成",
		chtml : title+"<br />确定要设定订单状态为<b>生产完成</b>？",
		win : parent,
		isAlert : true,
		iframeAuto : false,
		overlayAlpha : .5,
		iframeScroll : "auto",
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "  确定  ",
				onClick : function(w){
					$.post(
							"<?=U("InvoiceManager/setStatusProduced")?>",
							{id:id},
							function(data){
								if(data.status=="1"){
									top.Maya.Msg({
										type : "success",
										msg : "操作成功",
										call : function(){
											w.close();
											freshIframe();
										}
									});	
								}else{
									top.Maya.Msg(data.info);
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "  取消  "	,
				isCancel : true
			}
		]
	});	
}
function delOrderWork(){
	var selected = selectOrder();
	if(selected.o_status != "produced")return;
	var id = selected.id;
	var title = selected.p_name+"<br />订单号："+selected.o_number;
	new Maya.Box({
		text : "加工单作废",
		chtml : title+"<br />确定要设定订单状态为<b>生产完成</b>？",
		win : parent,
		isAlert : true,
		iframeAuto : false,
		overlayAlpha : .5,
		iframeScroll : "auto",
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "  确定  ",
				onClick : function(w){
					$.post(
							"<?=U("InvoiceManager/setStatusProduced")?>",
							{id:id},
							function(data){
								if(data.status=="1"){
									Maya.Msg({
										type : "success",
										msg : "操作成功",
										call : function(){
											w.close();
											freshIframe();
										}
									});	
								}else{
									Maya.Msg(data.info);
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "  取消  "	,
				isCancel : true
			}
		]
	});	
}
</script>
</head>
<body style="background: none;">
<div id="dbTool">
	<a href="#" id="btnedit" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="show()">查看详细</a>
	<a href="#" class="easyui-linkbutton" iconCls="icon-log" plain="true" onclick="getLabel()">加工单</a>
	<a href="#" class="easyui-linkbutton" iconCls="icon-ok" plain="true" onclick="produced()">生产完成</a>
	<!-- <a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="delOrderWork()">加工单作废</a> -->
	<a href="#" id="btnUnsel" class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="$('#tbl').datagrid('clearSelections')">取消选中</a>
	<span style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消选中)。</span>
</div>
<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<input type="hidden" name="s" id="s"
				value="/<?=MODULE_NAME?>/<?=ACTION_NAME?>/" />
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td height="30" align="right"><strong>日期范围：</strong></td>
					<td colspan="3">
						<input id="dstart" style="width: 130px;" type="text" class="easyui-datebox" name="dstart" value="<?=date ( "Y-m-d", strtotime ( "-30 day" ) )?>" />
						— <input id="dend" style="width: 130px;" class="easyui-datebox" type="text" name="dend" value="<?=date ( "Y-m-d")?>" />
					<td>
					</td>
				</tr>
				<tr>
					<td width="100" height="30" align="right"><strong>用户：</strong></td>
					<td width="120" align="right">
						<select id="uName" name="uName" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($Uarr as $rs):?>
							<option value="<?=$rs['id']?>"><?=$rs['u_name']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="80" height="30" align="right"><strong>订单状态：</strong></td>
					<td width="100" align="right">
						<select id="status" name="status" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($staArr as $rs):?>
							<option value="<?=$rs['status']?>"><?=$rs['display']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="100" align="right">
						<a href="#" class="easyui-linkbutton" onclick="javascript:filterData();" iconCls="icon-search">搜索</a>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<table id="tbl" data-options="singleSelect:true">
		<thead>
			<tr>
				<th field="o_number" align="left" width="150"><strong>编号</strong></th>
				<th field="userInfo" align="center" width="150"><strong>用户</strong></th>
				<th field="p_name" align="left" width="150"><strong>项目</strong></th>
				<th field="o_price" align="center" width="80"><strong>订单金额</strong></th>
				<th field="o_date" align="left" width="120"><strong>日期</strong></th>
				<th field="statusInfo" align="left" width="150"><strong>状态</strong></th>
				<th field="o_desc" align="left" width="120"><strong>备注</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>