<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	$('#btnedit').linkbutton('disable');
	$('#btndel').linkbutton('disable');	
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","我的订单列表","<?=U('DataList/getOrderListJson')?>","#dbTool");
});
function filterData(){
	var dstart = $('#dstart').datebox('getValue');
	var dend   = $('#dend').datebox('getValue');
	var status = $('#status').val();
	$.post(
			"<?=U('DataList/getOrderListJson')?>",
			{
				status:status,
				dstart:dstart,
				dend:dend,
				page:oPage.pageIndex,
				rows:oPage.pageSize
			},
			function(data){
					$('#tbl').datagrid('getPager').pagination({
						onSelectPage : function(pPageIndex, pPageSize) {
							//改变oPage的参数值，用于下次查询传给数据层查询指定页码的数据
							oPage.pageIndex = pPageIndex;
							oPage.pageSize = pPageSize;
							$.post(
									"<?=U('DataList/getOrderListJson')?>",
									{
										status:status,
										dstart:dstart,
										dend:dend,
										page:oPage.pageIndex,
										rows:oPage.pageSize
									},
									function(data){
										$("#tbl").datagrid("loadData",data);
									},'json'
							);
							//异步获取数据到javascript对象，入参为查询条件和页码信息
							//var oData = getAjaxDate("orderManageBuz","qryWorkOrderPaged",queryCondition,oPage);
							//使用loadDate方法加载Dao层返回的数据
							//$('#tt').datagrid('loadData',{"total":oData.page.recordCount,"rows":oData.data});
							
						}
					});
					$("#tbl").datagrid("loadData",data);
			},
			"json"
		);
	return false;
}
function show(){
	var selected = $('#tbl').datagrid('getSelections');
	if(selected.length > 1 || selected.length == 0){
		Maya.Msg("未选中，或选中数量超出限制。");
		return "";
	}
	var id = selected[0].id;
	new Maya.Box({
		text : "订单详细信息",
		url : "<?=U ( "DataList/showOrder" )?>/id/"+id,
		win : parent,
		width : 700,
		height : 220,
		btns : [
	    	{
				text : "    修改    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
				}	
			},
    		{
				text : "    确定    ",
				isCancel : true	
			}
			<?php if($_SESSION ['cmp'] ['g_manager'] == 1):?>
			,{
				text : ' 详细信息(内部)',
				onClick : function(w){
					w.getIframe().showAll(w,selected[0].offer_id);
					// _self.close();
				}	
			}
			<?php endif;?>
		]
	});
}
function delOrder(){
	var selected = $('#tbl').datagrid('getSelections');
	if(selected.length == 0){
		Maya.Msg("请选择订单【单击行即可】");
		return "";
	}
	if(selected.length > 1){
		Maya.Msg("未防止误操作，一次只可取消一笔订单。");
		return "";
	}
	var id = selected[0].id;
	if(selected[0].o_status === "cancel"){
		Maya.Msg("该订单已被取消。");
		return "";
	}
	if(selected[0].o_status !== "confirming" && selected[0].o_status !== "cancel"){
		Maya.Msg({
			type : "hits",
			msg : "<span style='color:#0000FF;'>该订单已通过审核，如需取消该订单，请与客服人员联系。</span>",
			call : null,
			sec : 4
		});
		return "";
	}
	var title = selected[0].p_name+"<br />订单号："+selected[0].o_number;
	new Maya.Box({
		text : "订单取消",
		chtml : "<b>确定要取消订单？</b><br />"+title,
		win : parent,
		isAlert : true,
		iframeAuto : false,
		overlayAlpha : .5,
		iframeScroll : "auto",
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "  确定  ",
				onClick : function(w){
					$.post(
							"<?=U("DataList/orderList")?>",
							{id:id},
							function(data){
								if(data.status=="1"){
									top.Maya.Msg({
										type : "success",
										msg : "操作成功",
										call : function(){
											w.close();
											freshIframe();
										}
									});	
								}else{
									top.Maya.Msg(data.info);
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "  取消  "	,
				isCancel : true
			}
		]
	});	
}
</script>
</head>
<body style="background: none;">
<div id="dbTool">
	<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true"
		onclick="show()">查看详细</a> <a href="#"
		class="easyui-linkbutton" iconCls="icon-cancel" plain="true"
		onclick="delOrder()">订单取消</a> <a href="#" id="btnUnsel"
		class="easyui-linkbutton" iconCls="icon-back" plain="true"
		onclick="$('#tbl').datagrid('clearSelections')">取消选中</a> <span
		style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消选中)。</span>
</div>
<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<input type="hidden" name="s" id="s"
				value="/<?=MODULE_NAME?>/<?=ACTION_NAME?>/" />
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="80" height="30" align="right"><strong>订单状态：</strong></td>
					<td width="100" align="right">
						<select id="status" name="status" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($staArr as $rs):?>
							<option value="<?=$rs['status']?>"><?=$rs['display']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="100" height="30" align="right"><strong>日期范围：</strong></td>
					<td><input id="dstart" type="text" class="easyui-datebox"
						name="dstart"
						value="<?=$_GET['dstart'] == "" ? date ( "Y-m-d", strtotime ( "-30 day" ) ) : $_GET['dstart']?>" />
						— <input id="dend" class="easyui-datebox" type="text" name="dend"
						value="<?=$_GET['dend'] == "" ? date ( "Y-m-d") : $_GET['dend']?>" />&nbsp;&nbsp;&nbsp;
						<a href="#" class="easyui-linkbutton"
						onclick="javascript:filterData();" iconCls="icon-search">搜索</a></td>
				</tr>
			</table>
		</form>
	</div>
	<table id="tbl" data-options="singleSelect:true">
		<thead>
			<tr>
				<th field="o_number" align="left" width="150"><strong>编号</strong></th>
				<th field="p_name" align="left" width="150"><strong>项目</strong></th>
				<th field="o_price" align="center" width="80"><strong>订单金额</strong></th>
				<th field="o_date" align="left" width="120"><strong>日期</strong></th>
				<th field="statusInfo" align="left" width="150"><strong>状态</strong></th>
				<th field="o_desc" align="left" width="120"><strong>备注</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>