<include file="Include:header" />
<link href="__PUBLIC__/Plugin/slider/css/slider.css" rel="stylesheet"
	type="text/css" />
<script type="text/javascript"
	src="__PUBLIC__/Plugin/slider/js/slider.js"></script>
<script type="text/javascript">
<!--
jQuery(document).ready(function($)
{
	/*$('.flexslider').flexslider({
        animation: "slide",
        slideshow: true,                //Boolean: Animate slider automatically
        slideshowSpeed: 4000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
        animationSpeed: 600
      });*/
});
//-->
</script>
<style>
<!--
#centerContent {
	clear: both;
	line-height: 2;
	margin: 0 auto;
	padding: 0px 0 0 0;
	position: relative;
	width: 940px;
	min-height: 420px;
}

#contact {
	clear: both;
	border-top: 1px solid #DDDDDD;
	width: 820px;
	height: 160px;
	margin: 0 auto;
	padding-left: 20px;
}

.section {
	clear: both;
	content: ".";
	display: block;
	margin: 20px 0;
	height: 320px;
	border-bottom: 1px dashed #DDDDDD;
}
.section img{
	width:480px;
	-webkit-box-shadow: 0px 1px 3px rgba(0,0,0,.5);
	-moz-box-shadow: 0px 1px 3px rgba(0,0,0,.5);
	box-shadow: 0px 1px 3px rgba(0,0,0,.5);
}
img.left {
	position: relative;
	float: left;
}

div.right {
	position: relative;
	text-align: center;
	float: right;
	width: 300px;
	margin: 80px 100px 0 0;
}

img.right {
	position: relative;
	float: right;
}

div.left {
	position: relative;
	text-align: center;
	float: left;
	width: 360px;
	margin: 100px 100px 0 0;
}

.section p {
	text-indent: 2em;
}

.section p.title {
	text-shadow: 0 1px 0 #dedede;
	text-indent: 2em;
	margin: 0px;
	font-size: 16px;
}

.section p.sub {
	margin: 0px;
	color: #888888;
	text-shadow: 0 1px 0 #FFFFFF;
	font-size: 15px;
}

.section ul {
	
}

.section ul li {
	color: #444;
	text-shadow: 0 1px 0 #FFFFFF;	
	line-height:30px;
	margin-left: 50px;
	list-style-type: circle;
}
-->
</style>
<include file="Include:toper" />
<div class="navigator">
	<div id="wrap">
		<div id="centerContent">
			<div id="content">
				<div class="section">
					<p class="title">“7788印刷报价软件”是专为印刷生产厂家量身定做的一款自动化ERP印刷软件。可以释放您的双手去做更有价值的事情；<strong>不会再</strong>因为手机占线而丢失新客户；<strong>也不会</strong>因为手工报价存在一定误差或再次报价时与之前报价不符而造成客诉；<strong>更不会</strong>因为做帐中出现遗漏订单而带来的损失。</p>
					<p>这一切就让“7788印刷报价软件”为您去做吧，让您的办公变得轻松自如、更加专业，从而获得更大的市场份额。</p>
					<ul type="circle">
						<li>您是否为每天都需要面对<strong>大量又枯燥</strong>的印刷报价而烦恼呢？</li>
						<li>您在计算过程中是否容易出现<strong>报价错误</strong>呢？</li>
						<li>您是否会因为固定成本的变化而去<strong>翻开账本去查找数据</strong>呢？</li>
						<li>您是否还在为<strong>业务范围的狭小</strong>而着急呢？</li>
						<li>未来的印刷将会向着<strong>电子商务</strong>时代而转型，您还能无动于衷吗？</li>
					</ul>
					<p class="title">美好的未来就在“7788印刷网”一步一步地为您实现。</p>
				</div>
				<div class="section">

					<div class="left">
						<p class="title">自助报价</p>
						<p class="sub">不用双手、不打电话也可为客户报价，将报价过程简化到极致。</p>
					</div>
					<img class="right" src="__PUBLIC__/Images/home/zzbj.jpg">
				</div>
				<div class="section">
					<img class="left" src="__PUBLIC__/Images/home/zxdd.jpg">
					<div class="right">
						<p class="title">在线订单</p>
						<p class="sub">全自动化办公，减轻您的负担。</p>
					</div>
				</div>
				<div class="section">
					<div class="left">
						<p class="title">单据打印</p>
						<p class="sub">全自动模式生成相关单据打印功能。</p>
					</div>
					<img class="right" src="__PUBLIC__/Images/home/djdy.jpg">
				</div>
				<div class="section">
					<img class="left" src="__PUBLIC__/Images/home/czmk.jpg">
					<div class="right">
						<p class="title">财务模块</p>
						<p class="sub">充值、做帐、收款等等再也不是问题。</p>
					</div>
				</div>
				<div class="section">
					<div class="left">
						<p class="title">仓储模块</p>
						<p class="sub">进销存，无需专业人员也可轻松搞定。</p>
					</div>
					<div class="right">
						<p class="title">个性应用</p>
						<p class="sub">
							公司网站建设，实现自动化、简单化、市场化转型；<br />个性定制，可根据客户需求定做其他应用程序
						</p>
					</div>
				</div>
				<!-- <div class="section">
					<img class="left" src="__PUBLIC__/Images/home/zzbj.jpg">
					<div class="right">
						<p class="title">个性应用</p>
						<p class="sub">
							公司网站建设，实现自动化、简单化、市场化转型；<br />个性定制，可根据客户需求定做其他应用程序
						</p>
					</div>
				</div> -->
			</div>
		</div>
	</div>
</div>
<include file="Include:footer" />
</body>
</html>