<include file="Include:header" />
<script language="JavaScript" type="text/javascript">
function $(){return document.getElementById?document.getElementById(arguments[0]):eval(arguments[0]);}
function getvalue(){
	var ps=$("ps").value;
	var kezhong=$("kezhong").value;
	$("shows").innerHTML=(ps/2*0.001346*kezhong).toFixed(3)+"MM";
}

</script>
</head>
<body style="background: none;">
	<div class="content">
		<div class="body_title">
			<h1>
				书脊厚度计算 <em>根据书籍画册的P数换算书的厚度</em>
			</h1>
		</div>
		<table border="0" cellpadding="0" cellspacing="0"
			class="tb">
			<tbody>
				<tr>
					<th width="171"><span id="summary">书籍</span>P数</th>
					<th width="264"><span id="summary">纸张</span>克重</th>
					<th width="134"><span id="summary">书籍</span>厚度</th>
				</tr>
				<tr align="center">
					<td><input name="ps" type="text" id="ps" onkeyup="getvalue()"
						size="7" maxlength="5"></td>
					<td><div style="position: relative; width: 64px;">
							<span style="overflow: hidden;"> <select style="width: 64px;"
								onchange="$('kezhong').value=this.value;getvalue();">
									<option value="35">35</option>
									<option value="40">40</option>
									<option value="45">45</option>
									<option value="49">49</option>
									<option value="50">50</option>
									<option value="52">52</option>
									<option value="55">55</option>
									<option value="60">60</option>
									<option value="65">65</option>
									<option value="70">70</option>
									<option value="75">75</option>
									<option value="80">80</option>
									<option value="85">85</option>
									<option value="90">90</option>
									<option value="100">100</option>
									<option value="105">105</option>
									<option value="120">120</option>
									<option value="128">128</option>
									<option value="130">130</option>
									<option value="140">140</option>
									<option value="150">150</option>
									<option value="157" selected="selected">157</option>
									<option value="160">160</option>
									<option value="170">170</option>
									<option value="180">180</option>
									<option value="190">190</option>
									<option value="200">200</option>
									<option value="210">210</option>
									<option value="220">220</option>
									<option value="230">230</option>
									<option value="240">240</option>
									<option value="250">250</option>
									<option value="300">300</option>
									<option value="350">350</option>
									<option value="400">400</option>
							</select>
							</span>


							<div
								style="z-index: 10; position: absolute; width: 42px; height: 20px; left: 3px; top: 1px;">
								<iframe
									style="position: absolute; z-index: -1; width: 37px; height: 16px; left: 1px; top: 1px; scrolling: no;"
									frameborder="0"></iframe>
								<input name="kezhong" id="kezhong"
									style="width: 37px; height: 16px; border: 0;" value="157"
									size="4" maxlength="4" onkeyup="getvalue()">
							</div>
						</div></td>
					<td id="shows">1.716MM</td>
				</tr>
			</tbody>
		</table>
	</div>
</body>
</html>