<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	$('#btnedit').linkbutton('disable');
	$('#btndel').linkbutton('disable');	
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","订单列表","<?=U('InvoiceManager/getOrderListJson')?>","#dbTool");
	$('#choseStatus').change(function(){
		//console.info($(this));
		if($(this)[0].checked == true){
			filterData('sel');
		}else{
			filterData('');
		}
	});
});
function filterData(type){
	var uName = $('#uName').val();
	var dstart = $('#dstart').datebox('getValue');
	var dend   = $('#dend').datebox('getValue');
	var status = $('#status').val();
	$.post(
			"<?=U('InvoiceManager/getOrderListJson')?>",
			{
				type:type,
				status:status,
				uName:uName,
				dstart:dstart,
				dend:dend,
				page:oPage.pageIndex,
				rows:oPage.pageSize
			},
			function(data){
					$('#tbl').datagrid('getPager').pagination({
						onSelectPage : function(pPageIndex, pPageSize) {
							//改变oPage的参数值，用于下次查询传给数据层查询指定页码的数据
							oPage.pageIndex = pPageIndex;
							oPage.pageSize = pPageSize;
							$.post(
									"<?=U('InvoiceManager/getOrderListJson')?>",
									{
										type:type,
										status:status,
										uName:uName,
										dstart:dstart,
										dend:dend,
										page:oPage.pageIndex,
										rows:oPage.pageSize
									},
									function(data){
										$("#tbl").datagrid("loadData",data);
									},'json'
							);
							//异步获取数据到javascript对象，入参为查询条件和页码信息
							//var oData = getAjaxDate("orderManageBuz","qryWorkOrderPaged",queryCondition,oPage);
							//使用loadDate方法加载Dao层返回的数据
							//$('#tt').datagrid('loadData',{"total":oData.page.recordCount,"rows":oData.data});
							
						}
					});
					$("#tbl").datagrid("loadData",data);
			},
			"json"
		);
	return false;
}

function selectOrder(){
	var selected = $('#tbl').datagrid('getSelections');
	if(selected.length == 0){
		Maya.Msg("请选择订单【单击行即可】");
		return "";
	}
	if(selected.length > 1){
		Maya.Msg("未防止误操作，一次只可操作一笔订单。");
		return "";
	}
	return selected[0];
}

function show(type){
	var sel = selectOrder();
	var id = sel.id;
	var btns = [{text : "    确定    ",isCancel : true	},{
		text : ' 详细信息(内部)',
		onClick : function(w){
			w.getIframe().showAll(w,sel.offer_id);
			// _self.close();
		}	
	}];
	if(sel == "")return;
	if(type != undefined && sel.o_status != "checking"){
		return;
	}
	if(type != undefined){
		btns = [{text : "    审核通过    ",onClick : function(w){w.getIframe().submitForm(w,1)}},
				{text : "    审核不通过    ",onClick : function(w){w.getIframe().submitForm(w,0)}},
				{text : ' 详细信息(内部)',onClick : function(w){w.getIframe().showAll(w,sel.offer_id);}},
				{text : "    取消    ",isCancel : true	}
		];
	}
	
	new Maya.Box({
		text : "订单详细信息",
		url : "<?=U ( "InvoiceManager/showOrder" )?>/id/"+id,
		win : parent,
		width : 700,
		height : 220,
		btns : btns,
		onClose:function(){
			$("#tbl").datagrid("reload");
		}
	});
}

function getOrder(type){
	var sel = selectOrder();
	if(sel == "")return;
	var id = sel.id;
	var title = "<b>确定要确认订单？</b><br />";
	if(type == undefined){
		if(sel.o_status != "confirming"){
			return;
		}
		//title = "<b>确定要确认订单？</b><br />";
	}else if(type != undefined){
		if(sel.o_status == "cancel" || sel.o_status == "over"){
			return;
		}
		title = "<b>确定要取消订单？</b><br />";
	}
	title += sel.p_name+"<br />订单号："+sel.o_number;
	new Maya.Box({
		text : "订单号："+sel.o_number,
		chtml : title,
		win : parent,
		isAlert : true,
		overlayAlpha : .5,
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "  确定  ",
				onClick : function(w){
					$.post(
							"<?=U("InvoiceManager/index")?>",
							{type:type,id:id},
							function(data){
								if(data.status=="1"){
									top.Maya.Msg({
										type : "success",
										msg : data.info,
										call : function(){
											w.close();
										}
									});	
								}else{
									top.Maya.Msg(data.info);
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "  取消  "	,
				isCancel : true
			}
		],
		onClose:function(){freshIframe();}
	});	
}
</script>
</head>
<body style="background: none;">
<div id="dbTool">
	<a href="#" id="btnedit" class="easyui-linkbutton" iconCls="icon-log" plain="true" onclick="show()">查看详细</a>
	<a href="#" class="easyui-linkbutton" iconCls="icon-ok" plain="true" onclick="getOrder()">确认接收</a>
	<a href="#" class="easyui-linkbutton" iconCls="icon-checkOk" plain="true" onclick="show('check')">订单审核</a>
	<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="getOrder('cel')">取消订单</a>
	<a href="#" id="btnUnsel" class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="$('#tbl').datagrid('clearSelections')">取消选中</a>
	<span style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消选中)。</span>&nbsp;&nbsp;
	<label style="color: #1A77C9; margin-left: 30px;"><input type="checkbox" id="choseStatus" name="choseStatus" />&nbsp;待处理状态</label>
</div>
<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<input type="hidden" name="s" id="s"
				value="/<?=MODULE_NAME?>/<?=ACTION_NAME?>/" />
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td height="30" align="right"><strong>日期范围：</strong></td>
					<td colspan="3">
						<input id="dstart" style="width: 130px;" type="text" class="easyui-datebox" name="dstart" value="<?=date ( "Y-m-d", strtotime ( "-30 day" ) )?>" />
						— <input id="dend" style="width: 130px;" class="easyui-datebox" type="text" name="dend" value="<?=date ( "Y-m-d")?>" />
					<td>
						
					</td>
				</tr>
				<tr>
					<td width="100" height="30" align="right"><strong>用户：</strong></td>
					<td width="120" align="right">
						<select id="uName" name="uName" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($Uarr as $rs):?>
							<option value="<?=$rs['id']?>"><?=$rs['u_name']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="80" height="30" align="right"><strong>订单状态：</strong></td>
					<td width="100" align="right">
						<select id="status" name="status" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($staArr as $rs):?>
							<option value="<?=$rs['status']?>"><?=$rs['display']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="100" align="right">
						<a href="#" class="easyui-linkbutton" onclick="javascript:filterData('');" iconCls="icon-search">搜索</a>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<table id="tbl"  data-options="singleSelect:true">
		<thead>
			<tr>
				<th field="o_number" align="left" width="150"><strong>编号</strong></th>
				<th field="userInfo" align="center" width="150"><strong>用户</strong></th>
				<th field="p_name" align="left" width="150"><strong>项目</strong></th>
				<th field="o_price" align="center" width="80"><strong>订单金额</strong></th>
				<th field="o_date" align="left" width="120"><strong>日期</strong></th>
				<th field="status" align="left" width="150"><strong>状态</strong></th>
				<th field="o_desc" align="left" width="120"><strong>备注</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>