<include file="Include:header" />
<link href="__PUBLIC__/Jquey.DatePicker/ui.datepicker.css" rel="stylesheet" type="text/css" />
<script src="__PUBLIC__/Jquey.DatePicker/ui.datepicker.js" type="text/javascript"></script>
<script language="javascript">
$(document).ready(function(){
	$("#dstart").datepicker();
	$("#dend").datepicker();
});
function show(id,type){
	new Maya.Box({
		text : "对应操作记录",
		url : "<?=U ( "MyUser/show" )?>/id/"+id+"/type/"+type,
		win : parent,
		width : 700,
		height : 220,
		btns : [
    		{
				text     : "    确定    ",
				isCancel : true	
			}
		]
	});
}
function chongzhi(){
	new Maya.Box({
		text : "充值预付款",
		url : "<?=U ( "MyUser/charge" )?>",
		win : parent,
		width : 500,
		height : 220,
		btns : [
    		{
    			text : "    提交    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
					// _self.close();
				}
			},{
				text     : "    取消    ",
				isCancel : true	
			}
		],
		onClose:function(){freshIframe();}
	});
}

</script>

<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<input type="hidden" name="s" id="s"
				value="Center/<?=MODULE_NAME?>/<?=ACTION_NAME?>/" />
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="100" height="30" align="right"><strong>日期范围：</strong></td>
					<td><input id="dstart" type="text" class="input_text easyui-datebox"
							name="dstart" value="<?=$_GET['dstart'] == "" ? date ( "Y-m-d", strtotime ( "-30 day" ) ) : $_GET['dstart']?>" /> — <input id="dend"
							class="input_text easyui-datebox" type="text" name="dend"
							value="<?=$_GET['dend'] == "" ? date ( "Y-m-d") : $_GET['dend']?>" />&nbsp;&nbsp;&nbsp;
						<a href="#" class="easyui-linkbutton"
						onclick="javascript:$('#form').submit();" iconCls="icon-search">搜索</a>
						<a href="#" class="easyui-linkbutton"
						onclick="chongzhi();" iconCls="icon-search">充值</a>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<div class="tag">充值记录</div>
	<div class="tagc" style="margin-bottom: 0; padding: 1px;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0"
			class="tb tblGrid">
			<thead>
				<tr bgcolor="#CCCCCC">
					<!-- 会员号 用户名 所在组 公司名称 地区 联系人 QQ 登录/报价  -->
					<th width="30" align="center"></th>
					<th align="left" width="120"><strong>账户</strong></th>
					<th align="left" width="120"><strong>目标账户</strong></th>
					<th align="center" width="100"><strong>汇款日期</strong></th>
					<th align="left" width="80"><strong>充值金额</strong></th>
					<th align="left" width="80"><strong>余额</strong></th>
					<th align="left" width="30"><strong>审核</strong></th>
				</tr>
			</thead>
			<tbody>
			<?php
			$i = 0;
			foreach ( $recordArr as $row ) :
				$i ++;
				$bg = $i % 2 == 0 ? 'bgcolor="#FAFAFA"' : "";
				?>
				<tr>
					<td align="center"><?=$i?></td>
					<td align="left"><?= $row['re_bankInfo'] ?></td>
					<td align="left"><?= $row['re_myBank'] ?></td>
					<td align="center"><?= $row['re_date'] ?></td>
					<td align="left"><?= $row['re_money'] ?></td>
					<td align="left"><?= $row['re_overage'] ?></td>
					<td align="left">
						<?php 
							if($row['re_status'] == 0){
								echo "<span style='color:#E4C600;'>审核中</span>";
							}else if($row['re_status'] == 1){
								echo "<span style='color:blue;'>成功</span>";
							}else{
								echo "<span style='color:red;'>失败</span>";
							}
						?>
					</td>
				</tr>
			<?php endforeach; ?>
        </tbody>
		</table>
		<!-- 分页文字 -->
		<div class="page-contain">
			<table width="100%">
				<tr>
					<td align="center" width="200">
						<!-- <input type="submit"
						class="maya_btn export_btn" value="导出Excel" /> <input
						type="submit" class="maya_btn import_btn" value="导入Excel" /> -->
					</td>
					<td align="right"><?=$page->printCount();$page->pageNormal();$page->printDropMenu();?></td>
				</tr>
			</table>
		</div>
	</div>
</div>
</body>
</html>