<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","我的订单列表","<?=U('Statistics/getOfferListJson')?>","#dbTool");
});
function filterData(){
	var uName = $('#uName').val();
	var dstart = $('#dstart').datebox('getValue');
	var dend   = $('#dend').datebox('getValue');
	$.post(
			"<?=U('Statistics/getOfferListJson')?>",
			{
				uName:uName,
				dstart:dstart,
				dend:dend,
				page:oPage.pageIndex,
				rows:oPage.pageSize
			},
			function(data){
					$('#tbl').datagrid('getPager').pagination({
						onSelectPage : function(pPageIndex, pPageSize) {
							oPage.pageIndex = pPageIndex;
							oPage.pageSize = pPageSize;
							$.post(
									"<?=U('Statistics/getOfferListJson')?>",
									{
										uName:uName,
										dstart:dstart,
										dend:dend,
										page:oPage.pageIndex,
										rows:oPage.pageSize
									},
									function(data){
										$("#tbl").datagrid("loadData",data);
									},'json'
							);
						}
					});
					$("#tbl").datagrid("loadData",data);
			},
			"json"
		);
	return false;
}
function show(id){
	var selected = $('#tbl').datagrid('getSelections');
	if(selected.length > 1 || selected.length == 0){
		Maya.Msg("未选中，或选中数量超出限制。");
		return "";
	}
	var id = selected[0].id;
	new Maya.Box({
		text : "报价详细信息",
		url : "<?=U ( "DataList/showOffer" )?>/id/"+id,
		win : parent,
		width : 700,
		height : 220,
		btns : [
    		{
				text     : "    确定    ",
				isCancel : true	
			}
			<?php if($_SESSION ['cmp'] ['g_manager'] == 1):?>
			,{
				text : ' 详细信息(内部)',
				onClick : function(w){
					w.getIframe().showAll(w,selected[0].offer_id);
					// _self.close();
				}	
			}
			<?php endif;?>
		]
	});
}

</script>
</head>
<body style="background: none;">
<div id="dbTool">
	<a href="#" id="btnUnsel" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="show()">查看详细</a>
	<span style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消选中)。</span>
</div>
<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="100" height="30" align="right"><strong>所属用户：</strong></td>
					<td width="100" align="right">
						<select id="uName" name="uName" class="input_text" style="width:140px;">
							<option value="">不限</option>
							<?php foreach ($Uarr as $rs):?>
							<option value="<?=$rs['id']?>"><?=$rs['u_name']?></option>
							<?php endforeach;?>
						</select>
					</td>
					<td width="100" align="right"><strong>日期范围：</strong></td>
					<td>
						<input id="dstart" type="text" class="easyui-datebox" name="dstart" value="<?=date ( "Y-m-d", strtotime ( "-30 day" ) )?>" />
						— <input id="dend" class="easyui-datebox" type="text" name="dend" value="<?=date ( "Y-m-d")?>" />&nbsp;&nbsp;&nbsp;
					<td>
						<a href="#" class="easyui-linkbutton" onclick="javascript:filterData();" iconCls="icon-search">搜索</a>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<table id="tbl">
		<thead>
			<tr>
				<th field="p_name" align="left" width="150"><strong>报价项目</strong></th>
				<th field="o_size" align="left" width="150"><strong>尺寸</strong></th>
				<th field="o_amount" align="center" width="80"><strong>数量</strong></th>
				<th field="o_papePrice" align="center" width="60"><strong>纸价</strong></th>
				<th field="o_pro_price" align="center" width="80"><strong>后加工费用</strong></th>
				<th field="o_printPrice" align="center" width="60"><strong>印刷费</strong></th>
				<th field="o_price" align="center" width="100"><strong>最终报价</strong></th>
				<th field="userInfo" align="center" width="100"><strong>用户名</strong></th>
				<th field="o_date" align="left" width="120"><strong>报价时间</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>