<include file="Include:Header" />
<script language="javascript">
$(document).ready(function(){
})
</script>
<style type="text/css">
html {
	background: none;
}

.tbb {
	border-collapse: collapse;
}

.gray {
	font-weight: bold;
	background: #f7f7f7;
}

.tbb td {
	padding: 5px;
	font-size: 12px;
	border: 1px solid #999;
}

.tbb th {
	padding: 5px;
	font-size: 13px;
	background: #efefef;
	border: 1px solid #999;
}

.input_text {
	width: 95%;
}
</style>
</head>
<body>
	<div class="content">
		<div class="tag">个人账户信息</div>
		<div class="tagc">
			<table border="0" cellspacing="0" cellpadding="0"
				style="width: 100%; margin: 10px auto;" class="tbb">
				<tr>
					<td class="gray" height="30" width="100" align="right">所在用户组：</td>
					<td width="300"><?=$rs['g_name']?></td>
					<td class="gray" height="30" width="100" align="right">账户余额：</td>
					<td><?=$rs['curr_maney']?></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">信用额度：</td>
					<td><?=$rs['min_maney']?></td>
					<td class="gray" align="right">可用额度：</td>
					<td><?=$rs['avai_maney']?></td>
				</tr>
				<tr>
					<td class="gray" height="30" align="right">定金比例：<br />优惠比例：</td>
					<td><?=$rs['front_maney_percent']?>%<br /><?=$rs['tip_percent']?>%</td>
					<td class="gray" align="right">报价次数：</td>
					<td><?=$ofTotal['total']?></td>
				</tr>
				<tr>
					<td class="gray" height="50" align="right">未完成订单数：<br />总金额：</td>
					<td><?=$odTotalIng['total']?> <br /> <?=$odTotalIng['sumManey'] == "" ? 0 : $odTotalIng['sumManey']?></td>
					<td class="gray" align="right">已完成订单数：<br />总金额：</td>
					<td><?=$odTotalOver['total']?> <br /> <?=$odTotalOver['sumManey'] == "" ? 0 : $odTotalOver['sumManey']?></td>
				</tr>
			</table>
		</div>
	</div>
</body>
</html>