<include file="Include:Header" />
<script src="__PUBLIC__/js/initcity.js" type="text/javascript"></script>
<script language="javascript">
$(document).ready(function(){
	pc_init();
	$("#id").attr("value",'<?=$rs['id']?>');
	$("#company").attr("value",'<?=$rs['u_company']?>');
	$("#shengfen").html('<?=$rs['u_province']?>');
	$("#chengshi").html('<?=$rs['u_city']?>');
	$("#tel").attr("value",'<?=$rs['u_tel']?>');
	$("#manager").attr("value",'<?=$rs['u_manager']?>');
	$("#phone").attr("value",'<?=$rs['u_phone']?>');
	$("#addr").attr("value",'<?=$rs['u_address']?>');
	$("#email").attr("value",'<?=$rs['u_email']?>');
	$("#province").attr("disabled",true);
	$("#city").attr("disabled",true);
	$("#isedit").change(function() {
		if($(this)[0].checked == true){
			$("#province").attr("disabled",false);
			$("#city").attr("disabled",false);
		}else{
			$("#province").attr("disabled",true);
			$("#city").attr("disabled",true);
		}
	}); 
})
function submitForm(){
	Maya.Msg({
	    msg : "正在提交中，请稍后....",
	    sec : 1.5,
  	});
    $.post(
            "<?=U(MODULE_NAME.'/'.ACTION_NAME)?>",
            $("#form").formSerialize(),
            function(data){
                    if(data.data == "success"){
                            Maya.Msg({
                                    type : "success",
                                    msg : data.info,
                                    sec : 1.5,
                                    call : function(){
                                    	location.reload();
                                    }
                            });
                    }else{
                            Maya.Msg({
                                    type : "fail",
                                    msg : data.info
                            });
                    }
            },
            "json"
    );
	return false;
}
</script>
<style type="text/css">
html {
	background: none;
}

.tbb {
	border-collapse: collapse;
}

.gray {
	font-weight: bold;
	background: #f7f7f7;
}

.tbb td {
	padding: 5px;
	font-size: 12px;
	border: 1px solid #999;
}

.tbb th {
	padding: 5px;
	font-size: 13px;
	background: #efefef;
	border: 1px solid #999;
}

.input_text {
	width: 95%;
}
</style>
</head>
<body>
	<div class="content">
		<form id="form" name="form">
			<input type="hidden" id="id" name="id" />
			<div class="tag">个人信息维护</div>
			<div class="tagc" style="margin-bottom: 0;">
				<div class="form_pad_10">
					<table border="0" cellspacing="0" cellpadding="0" class="tbb" style="width: 100%; margin: 10px auto;">
						<tr>
							<td class="gray" height="30" align="right">公司名称：</td>
							<td><input id="company" name="company" type="text"
								class="input_text" style="width: 200px;" />&nbsp;<span
								class="mustIn">*</span>&nbsp;贵公司名称</td>
							<td class="gray" height="30" align="right">公司电话：</td>
							<td><input name="tel" type="text" class="input_text" id="tel"
								style="width: 200px;" /></td>
						</tr>
						<tr>
							<td class="gray" height="30" align="right">联系人：</td>
							<td><input name="manager" type="text" class="input_text"
								id="manager" style="width: 200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;联系人姓名</td>
							<td class="gray" height="30" align="right">联系人电话：</td>
							<td><input name="phone" type="text" class="input_text" id="phone"
								style="width: 200px;" />&nbsp;<span class="mustIn">*</span>&nbsp;联系人电话</td>
						</tr>
						<tr>
							<td class="gray" height="30" align="right">所在地区：</td>
							<td>&nbsp;&nbsp;<label id="shengfen"></label><label id="chengshi"></label>&nbsp;&nbsp;&nbsp;
								<label><input type="checkbox" id="isedit" name="isedit" />修改</label>
								<select id="province" name="province"></select><select id="city"
								name="city"></select>
							</td>
							<td class="gray" height="30" align="right">常用邮箱：</td>
							<td><input name="email" type="text" class="input_text" id="email"
								style="width: 200px;" /></td>
						</tr>
						<tr>
							<td class="gray" height="30" align="right">公司地址：</td>
							<td colspan="3"><input name="addr" type="text" class="input_text" id="addr"
								style="width: 400px;" /></td>
						</tr>
					</table>
				</div>
			</div>
			<div class="page-contain"  style="margin-bottom: 5px;">
				<table width="100%">
					<tr>
						<td align="center" width="150">
						<a href="javascript:void(0);" onclick="javascript:submitForm();" iconCls="icon-ok" class="easyui-linkbutton">修改</a></td>
						<td align="right">&nbsp;</td>
					</tr>
				</table>
			</div>
		</form>
	</div>
</body>
</html>