<include file="Include:header" />
<script src="__PUBLIC__/js/index_load.js" type="text/javascript"></script>
<script language="javascript">
$(document).ready(function(){
	$('.bgloader').fadeOut(500);
});
</script>
<include file="Include:toper" />
<div class="bgloader"></div>
<!-- left -->
<div data-options="region:'west'" border="true" title="菜单"  split="true"
	style="width: 170px; overflow: hidden;">
	<include file="Include:leftmenu" />
</div>
<!-- center 无锡市宸铭商务印刷有限公司-印刷报价系统-->
<div data-options="region:'center'" title="" border="true"  split="false"
	style="overflow: hidden;">
	<div id="tabs" class="easyui-tabs" data-options="fit:true,border:false,plain:true"
		style="overflow: hidden;">
		<div title="首页" id="home" data-options="closable:false" style="overflow: hidden;">
			<iframe  frameborder="0" allowtransparency="true" scrolling="no" style="width: 100%; height: 100%;" src="<?=U("Index/sysHome")?>"></iframe>
		</div>
	</div>
</div>
<?php if($_SESSION ['cmp']['g_manager'] == 1){?>
<div data-options="region:'east'" border="true" split="true" title="管理员菜单"
	style="width: 160px;overflow: hidden;">
	<include file="Include:rightmenu" />
</div>
<?php }?>
<!--  background: url(images/foot_bg.png) repeat-x; background: url(images/bg.jpg) repeat;-->

<div region="south" title="" split="false" border="false"
	style="height: 33px;/*background: url(__PUBLIC__/images/tabs-sprite.gif) repeat-x right -201px;*/">
	<include file="Include:footer" />
</div>
<div id="mm" class="easyui-menu" style="width: 150px;">
	<div id="mm-tabclose">关闭</div>
	<div id="mm-tabcloseall">全部关闭</div>
	<div id="mm-tabcloseother">除此之外全部关闭</div>
	<div class="menu-sep"></div>
	<div id="mm-tabcloseright">当前页右侧全部关闭</div>
	<div id="mm-tabcloseleft">当前页左侧全部关闭</div>
	<div class="menu-sep"></div>
	<div id="mm-fresh">刷新</div>
</div>
</body>
</html>