<include file="Include:header" />
<style type="text/css">
html {
	background: #fff;
}

ul {
	list-style-type: none;
	margin: 0px;
}

ul li {
	padding: 0px;
}

ul li a {
	line-height: 13px;
	font-size: 13px;
}

ul li div {
	margin: 3px 5px;
	padding: 1px 0 1px 5px;
	border: 1px solid #fff;
}

ul li div {
	margin: 2px 0px;
	padding: 3px 0 3px 4px;
}

ul li div.hover {
	cursor: pointer;
	border: 1px solid #dedede;
	background: url(__PUBLIC__/images/tbbg.png) repeat-x;
}

ul li div.hover a {
	color: #416AA3;
}

ul li div.selected {
	background: #E0ECFF;
	background: #FBEC88;
	background: url(__PUBLIC__/images/tbbg.png) repeat-x;
	cursor: pointer;
	border: 1px solid #dedede;
}

ul li div.selected a {
	color: #444;
	font-weight: bold;
}
</style>
<script language="javascript">
$(document).ready(function(){
	//$('#cc').combogrid('setValues',[1,2]);
	//setCheckBox("main_ched","ched");
	$("#proTree").tree({
		method:'GET',
	    animate: true,
	    //lines:true,
	    checkbox:true,
	    url : "<?=U('Process/getPro4TreeJson')?>",
		onLoadError:function(){
			parent.Maya.Msg("后加工工序列表加载失败，请稍后再试。");
		},
		onBeforeExpand:function(node){
			//$('#cam_tree').tree('options').url = "<?=U('VisualGated/getJosnData4IndexTree')?>/id/"+node.id+"/type/"+node.attributes;
			//alert("index.php?s=/System/treeJson/id/"+node.id+"/type/"+node.attributes);
		},
		onClick:function(node){
	        $(this).tree('toggle', node.target);
		},
		onLoadSuccess:function(){
			<?php if(count($proArr) > 0){?>var node;<?php } ?>
			<?php for ($i = 0;$i < count($proArr);$i++):?>
				node = $("#proTree").tree('find', <?=$proArr[$i]?>);
				$("#proTree").tree('check',node.target);
			<?php endfor;?>
		}
	});
	<?php foreach($checArr as $k):?>
		$("#ched_<?=$k['id']?>").attr("checked",true);
		//// echo json_encode(explode(",", $row['pa_attr_attr']));
		<?php if($k['id'] == 37){?>
			$('#37').combotree('setValues',[<?php echo $k['pa_attr_attr'];?>])
		<?php continue;}?>
		$('#<?=$k['id']?>').combogrid('setValues',[<?php echo $k['pa_attr_attr'];?>])
	<?php endforeach;?>
});
function submitForm(w){
	var nodes = $('#proTree').tree('getChecked');
	var s = '';
	if(nodes.length != 0){
		for(var i=0; i<nodes.length; i++){
			
			if (s != '') s += ',';
			s += nodes[i].id;
			//s += nodes[i].text + "&" + nodes[i].attributes;
			/*if(nodes[i].attributes != undefined){
				s += nodes[i].id + "#" + nodes[i].attributes;
			}else{
				s += nodes[i].id;
			}*/
		}
	}
	var da = $("#form").formSerialize();
	da += "&pro="+s+"";
	//console.info(da);return;
	$.post(
			"<?=U(MODULE_NAME.'/'.ACTION_NAME)?>",
			da,
			function(data){
				if(data.status=="1"){
					Maya.Msg({
						type : "success",
						msg : "操作成功",
						call : function(){
							//parent.location.reload();	
							w.close();
							//console.info("1111");
							freshIframe();
						}	
					});
				}else{
					Maya.Msg(data.info);	
				}
			},
			"json"
		);
	return true;
}
</script>
<div id="form_add_point" class="content">
	<form id="form" name="form">
		<input type="hidden" name="id" id="id" value="<?=$_GET['id']?>" />
		<table style="width: 100%;" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<td valign="top">
					<div class="tag">基本属性</div>
					<table style="height: 30px; height: 400px;" border="0"
						cellspacing="0" cellpadding="0" class="tb">
						<thead>
							<tr>
								<th width="30"><input type="checkbox" name="main_ched"
									id="main_ched" /></th>
								<th width="120" align="center">名称</th>
								<th width="80" align="center">可选属性</th>
							</tr>
						</thead>
							<?php foreach ($attrArr as $row):?>
							<tr>
							<td width="30" align="center"><input type="checkbox"
								name="ched[]" id="ched_<?=$row['id']?>" value="<?=$row['id']?>" /></td>
							<td width="120" align="center"><?=$row['a_name']?></td>
							<td width="80" align="center">
									<?php if(strpos($row['a_name'],'尺寸') !== false){?>
										<input id="<?=$row['id']?>" name="<?=$row['id']?>[]"
								class="easyui-combogrid" style="width: 250px;"
								data-options="
											panelWidth: 500,  
									        multiple: true,  
									        idField: 'id',  
									        textField: 's_name',  
									        url: '<?=U('PageSize/getAllPaperSize4Json')?>', 
									        fitColumns: true, 
									        columns: [[  
									            {field:'ck',checkbox:true},  
									            {field:'s_name',title:'名称',width:110},  
									            {field:'s_length',title:'长度',width:50},
									            {field:'s_width',title:'宽度',width:50},
									            {field:'s_desc',title:'备注',width:100} 
									        ]]" />
									 <?php }else if(strpos($row['a_name'],'纸张') !== false){?>
									<select id="<?=$row['id']?>" name="<?=$row['id']?>[]"
								class="easyui-combotree" style="width: 250px;"
								data-options="url:'<?=U('Paper/getPaper4TreeJson')?>/typeId/<?=$checArr[0]['p_type']?>',animate:true,multiple: true">
							</select>
									 <?php }else if(strpos($row['a_name'],'数量') === false){?>
									 <input id="<?=$row['id']?>" name="<?=$row['id']?>[]"
								class="easyui-combogrid" style="width: 250px;"
								data-options="
											panelWidth: 300,  
									        multiple: true,  
									        idField: 'id',  
									        textField: 'a_name',  
									        url: '<?=U('Product/getAttributeArr')?>/id/<?=$row['id']?>', 
									        fitColumns: true, 
									        columns: [[  
									            {field:'ck',checkbox:true},  
									            {field:'a_name',title:'名称',width:110},
									            {field:'a_desc',title:'备注',width:100} 
									        ]]" />
									<?php }?>
        						</td>
						</tr>
							<?php endforeach;?>
					</table>
				</td>
				<td width="10"></td>
				<td width="300" valign="top">
					<div class="tag">后加工工序</div>
					<div class="tagc"
						style="padding: 0; height: 420px; overflow-x: auto;">
						<ul id="proTree"></ul>
					</div>
				</td>
			</tr>
		</table>
	</form>
</div>
</body>
</html>