<include file="Include:header" />
<script language="javascript">
var oPage = {pageIndex:1,pageSize:10};
$(document).ready(function(){
	//$(".chosen").chosen();
	$('#btnedit').linkbutton('disable');
	$('#btndel').linkbutton('disable');	
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","报价项目列表","<?=U('Product/getDataGridData')?>","#dbTool");
	
});

function filterData(){
	var p_name = $('#p_name').val();
	var cate_id = $('#cate_id').val();
	var type_id = $('#type_id').val();
	var process_id = $('#process_id').val();
	var status = $('#status').val();
	//p_name  cate_id type_id  process_id  status
	$.post(
			"<?=U('Product/getDataGridData')?>",
			{
				p_name:p_name,
				cate_id:cate_id,
				type_id:type_id,
				process_id:process_id,
				status:status,
				page:oPage.pageIndex,
				rows:oPage.pageSize
			},
			function(data){
					$('#tbl').datagrid('getPager').pagination({
						displayMsg:'当前显示从 [{from}] 到 [{to}] 共[{total}]条记录',
						onSelectPage : function(pPageIndex, pPageSize) {
							//改变oPage的参数值，用于下次查询传给数据层查询指定页码的数据
							oPage.pageIndex = pPageIndex;
							oPage.pageSize = pPageSize;
							//定义查询条件
							/*var queryCondition = {
									id:id,
									name_index:name_index,
									cons_card_num:cons_card_num,
									dep_name:dep_name,
									team_name:team_name
								};*/
							$.post(
									"<?=U('Product/getDataGridData')?>",
									{
										p_name:p_name,
										cate_id:cate_id,
										type_id:type_id,
										process_id:process_id,
										status:status,
										page:oPage.pageIndex,
										rows:oPage.pageSize
									},
									function(data){
										$("#tbl").datagrid("loadData",data);
									},'json'
							);
							//异步获取数据到javascript对象，入参为查询条件和页码信息
							//var oData = getAjaxDate("orderManageBuz","qryWorkOrderPaged",queryCondition,oPage);
							//使用loadDate方法加载Dao层返回的数据
							//$('#tt').datagrid('loadData',{"total":oData.page.recordCount,"rows":oData.data});
							
						}
					});
					$("#tbl").datagrid("loadData",data);
			},
			"json"
		);
	return false;
}

function getSelected(num){
	var selected = $('#tbl').datagrid('getSelections');
	//console.info(selected[0].name);
	if(num != undefined){
		if(selected.length == 0){
			parent.Maya.Msg("请选择操作项【单击行即可】");
			return "";
		}
		if(selected.length > num){
			parent.Maya.Msg("所选数量超出操作限制。");
			return "";
		}
	}
	var id = "";
	for(var i = 0 ; i < selected.length;i++){
		id += selected[i].id;
		id += i+1 == selected.length ? "" : ","
	}
	return id;
}

function submitForm(type){
	var id = 0;
	var title = "添加";
	if(type == "edit"){
		var id = getSelected(1);
		if(!id){
			return;
		}
		title = "修改";
	}
	new Maya.Box({
		text : "报价项目"+title,
		url : "<?=U ( "Product/postCheck" )?>/type/"+type+"/id/"+id,
		win : parent,
		width : 600,
		height : 220,
		btns : [
    		{
				text : "    确定    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
					// _self.close();
				}	
			},
			{
				text : "    取消    ",
				onClick : function(w){
    				w.close();
				}	
			}
		]
	});
}

function updateAttr(){
	var id = getSelected(1);
	if(!id){
		return;
	}
	new Maya.Box({
		text : "报价项目属性设置",
		url : "<?=U ( "Product/setAttr" )?>/id/"+id,
		win : parent,
		width : 720,
		height : 220,
		btns : [
    		{
				text : "    确定    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
					// _self.close();
				}	
			},
			{
				text : "    取消    ",
				onClick : function(w){
    				w.close();
				}	
			}
		]
	});
}

function  del(){
	var selected = $('#tbl').datagrid('getSelections');
	//var id = getSelected();
	//if(!id){
	//	return;
	//}
	var id = "";
	var title = "";
	for(var i = 0 ; i < selected.length;i++){
		title += "<b>"+(i+1)+".</b>"+selected[i].p_name;
		title += i+1 == selected.length ? "" : ";&nbsp;&nbsp;&nbsp;";
		title += (i+1)%3 == 0 ? "<br />" : "";
		id += selected[i].id;
		id += i+1 == selected.length ? "" : ",";
	}
	new Maya.Box({
		text : "删除记录",
		chtml : "<b>确定要删除以下报价项目信息？</b><br />"+title+"",
		win : parent,
		isAlert : true,
		iframeAuto : false,
		overlayAlpha : .5,
		iframeScroll : "auto",
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "确定"	,
				onClick : function(w){
					$.post(
							"<?=U("Product/postCheck")?>",
							{
								type:'del',
								id:id
							},
							function(data){
								if(data.status=="1"){
									parent.Maya.Msg({
										type : "success",
										msg : "操作成功",
										call : function(){
											w.close();
											freshIframe();
										}
									});	
								}else{
									parent.Maya.Msg({
				                       type : "fail",
				                       msg : data.info
				               		});
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "取消"	,
				isCancel : true
			}
		]
	});	
}
function formatStatus(val,row){
	if (val == 0){  
        return '<a href="#" title="停用" iconCls="icon-no" plain="true"><img src="__PUBLIC__/images/center/icons/cross_circle.png" /></a>';  //
    } else {  
        return '<a href="#" title="启用" iconCls="icon-no" plain="true"><img src="__PUBLIC__/images/center/icons/tick_circle.png" /></a>';    
    }  
}
</script>
<div id="dbTool">
	<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="submitForm('add')">添加</a>
	<a href="#" id="btnedit" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="submitForm('edit')">修改</a>
	<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="del()">删除</a>|
	<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-perf" plain="true" onclick="updateAttr()">属性设置</a>
	<!-- <a href="#" class="easyui-linkbutton" iconCls="icon-outdepot" plain="true" onclick="printCard()">导出</a> -->
	<a href="#" id="btnUnsel" class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="$('#tbl').datagrid('clearSelections')">取消选中</a>
	<span style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消)。</span>
	<!--|
	<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-perf" plain="true" onclick="updateAttr()">属性设置</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-print" plain="true" onclick="printCard()">打印</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-depotkey" plain="true"  onclick="printCard()">导入</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-outdepot" plain="true"  onclick="printCard()">导出</a>-->
</div>
<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" name="form">
			<table border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="100" height="30" align="right">项目名称：</td>
					<td>
						<select class="chosen" name="p_name" id="p_name" 
						panelHeight="200" style="width: 150px; margin-top: 5px;">
							<option value="">不限</option>
							<?php foreach ($proArr as $key): ?>
								<option value="<?= $key['id'] ?>"
								<?php if($_GET['p_name'] == $key['id']){echo 'selected="selected"';}?>><?= $key['p_name'] ?></option>
							<?php endforeach; ?>
						</select>	
					</td>
					<td width="80" align="right">属性类别：</td>
					<td><select class="chosen" name="type_id" id="type_id" style="width: 100px; margin-top: 5px;">
							<option value="">不限</option>
							<?php foreach ($typeArr as $key): ?>
								<option value="<?= $key['id'] ?>"
								<?php if($_GET['type_id'] == $key['id']){echo 'selected="selected"';}?>><?= $key['t_name'] ?></option>
							<?php endforeach; ?>
						</select></td>
					<td width="80" align="right"></td>
					<td></td>
					<!-- <td width="80" align="right">类别：</td>
					<td><select class="chosen" name="cate_id" id="cate_id"
						panelHeight="200" style="width: 150px; margin-top: 5px;">
							<option value="">不限</option>
							<?php foreach ($cateArr as $key): ?>
								<option value="<?= $key['id'] ?>"
								<?php if($_GET['cate_id'] == $key['id']){echo 'selected="selected"';}?>><?= $key['t_name'] ?></option>
							<?php endforeach; ?>
						</select></td> -->
				</tr>
				<tr>
					<td align="right">启用：</td>
					<td><select name="status" id="status" style="width: 150px; margin-top: 5px;">
							<option value="">不限</option>
							<option value="1">启用</option>
							<option value="0">停用</option>
						</select></td>
					<td align="right"></td>
					<td><a href="#" class="easyui-linkbutton" iconCls="icon-search"
						onclick="javascript:filterData();">搜索</a></td>
					<td height="30" align="right"></td>
					<td></td>
				</tr>
			</table>
		</form>
	</div>
	<table id="tbl">
		<thead>
			<tr>
				<th field="p_name" width="120" align="left"><strong>报价项目名称</strong></th>
				<th field="category_name" align="left" width="50"><strong>类别</strong></th>
				<th field="type_name" align="left" width="100"><strong>属性类别</strong></th>
				<th field="attrCount" align="left" width="60"><strong>基础属性</strong></th>
				<th field="unit_name" align="left" width="40"><strong>单位</strong></th>
				<!-- <th field="processCount" align="left" width="60"><strong>后加工</strong></th> -->
				<th field="p_lastDate" align="left" width="150"><strong>更新时间</strong></th>
				<th field="p_index" width="40" align="center"><strong>排序</strong></th>
				<th field="p_status" width="40" align="center" formatter="formatStatus"><strong>启用</strong></th>
				<th field="p_desc" align="left" width="150"><strong>备注</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>