<include file="Include:header" />
<script language="javascript">
function submitCheck(){
	<?php if($_SESSION['cmp']): ?>
	if( $("#length").val()=="" ){
		Maya.Msg("请填写 <strong>自定义长</strong>！");
		$("xx").focus();
		return false;
	}
	if($("#width").val()=="" ){
		Maya.Msg("请填写 <strong>自定义宽</strong>！");
		$("yy").focus();
		return false;
	}
	if($("#shuliang").val()==""){
		Maya.Msg("请填写 <strong>数量</strong>！");
		$("#shuliang").focus();
		return false;
	}
	$.post(
			"<?=U(MODULE_NAME.'/'.ACTION_NAME)?>",
			$("#myform").formSerialize(),
			function(data){
				if(data.status=="1"){
					Maya.Msg({
                        type : "success",
                        msg : data.info,
                        sec : 1.5,
                        call : function(){
                        	console.info(data.data);
                        }
               		 });
				}else{
					Maya.Msg({
                        type : "fail",
                        msg : data.info
                });	
				}
			},
			"json"
		);
	return false;
	<?php else:?>
		loginBtn('<?=U ( "Login/panel" )?>');
		return false;
	<?php endif;?>
}
//单选
function disCheck(the,str){
	if (the.checked){
		$("#jiafengmian").attr("checked",true);
		$("#jiafengmian").attr("disabled",true);
	}else{
		$("#jiafengmian").attr("checked",false);
		$("#jiafengmian").attr("disabled",false);
	}
}
//显示后加工后附加XY值
function showCheck(the,str){
	if (the.checked){
		$("#"+str).css("display","inline");
	}else{
		$("#"+str).css("display","none");
	}
}

</script>
</head>
<body>
	<div class="content">
		<div class="body_title">
			<h1>
				便签表格自动报价 <em>各类便签、信纸、表格、笔记本</em>
			</h1>
		</div>
		<form action="" method="post" name="myform" id="myform"
			onsubmit="return CheckForm1();">
			<input type="hidden" id="pid" name="pid" value="{$pid}">
			<div class="tag">筛选</div>
			<div class="tagc">
				<table width="100%" border="0" align="center" cellpadding="0"
					cellspacing="0" class="tb_big">
					<tbody>
						<tr>
							<th>成品尺寸（长×宽）MM</th>
							<th>印刷数量</th>
							<th>每本页数</th>
							<th>单双面</th>
							<th>印刷颜色</th>
							<th>材料名称</th>
							<th>材料克重</th>
						</tr>
						<tr>
							<td><select name="chicun" id="chicun">
							<?php foreach ($sizeArr as $row):?>
								<option value="<?=$row['s_length']."x".$row['s_width']?>"><?=$row['s_name']?></option>
							<?php endforeach;?>
									<!-- <option value="88*128">72开(88×128)</option>
									<option value="105*145">64开(105×145)A6</option>
									<option value="105*190">48开(105×190)</option>
									<option value="210*140" selected="selected">32开(210×140)A5</option>
									<option value="210*285">16开(210×285)A4</option>
									<option value="420*285">8开(420×285)A3</option>
									<option value="95*130">正度64开(95×130)</option>
									<option value="95*180">正度48开(95×180)</option>
									<option value="190*130">正度32开(190×130)</option>
									<option value="265*190">正度16开(265×190)</option>
									<option value="265*380">正度8开(265×380)</option> -->
							</select>&nbsp;&nbsp;&nbsp; <br />
							<label><input name="isdiy" type="checkbox" id="isdiy" value="1" onclick="showCheck(this,'ccxy')"><font color="#FF0000">自定义尺寸</font></label>
							<span id="ccxy" style="display:none;margin:5px 0 0 10px;"> <input name="xx" type="text" id="xx" size="5" value="210" class="inputs"> X 
								<input name="yy" type="text" id="yy" size="5" value="140" class="inputs"> mm
							</span></td>
							<td><input name="shuliang" type="text" id="shuliang" value="200"
								class="input_text" size="8" maxlength="7">本</td>
							<td>
									<select id="pages" name="pages" style="width: 100px;" onchange="$('#mypages').val(this.value);">
										<option value="50">50页/本</option>
										<option value="100" selected="selected">100页/本</option>
										<option value="150">150页/本</option>
										<option value="200">200页/本</option>
									</select> <input name="mypages" id="mypages" class="input_text" style="width: 44px;" value="100" size="4" maxlength="4">
							</td>
							<td><select name="danshuang">
									<option value="单面">单面</option>
									<option value="双面">双面</option>
							</select></td>
							<td><select id="ysys" name="ysys">
									<option value="单色" selected="">单色</option>
									<option value="双色">双色</option>
									<option value="彩色">彩色</option>
							</select></td>
							<td><!-- <select id="cailiao" name="cailiao">
									<option value="4">书写纸</option>
									<option value="5">双胶纸</option>
									<option value="7">白卡纸(双白)</option>
									<option value="8">色打纸</option>
									<option value="9">牛皮纸</option>
							</select> --><select name="cailiao" id="cailiao">
								<?php foreach($materArr as $row):?>
									<option value="<?=$row['m_name']?>"><?=$row['m_name']?></option>
								<?php endforeach;?>
							</select></td>
							<td><select id="kezhong" name="kezhong">
									<option value="55">55克</option>
									<option value="60">60克</option>
									<option value="70">70克</option>
									<option value="80">80克</option>
									<option value="100">100克</option>
									<option value="120">120克</option>
									<option value="140">140克</option>
									<option value="160">160克</option>
									<option value="200">200克</option>
									<option value="250">250克</option>
							</select></td>
						</tr>
				
				</table>
			</div>
			<div class="tag">后道工序选择</div>
			<div class="tagc" style="margin-bottom: 0;">
				<table width="100%" border="0" align="center" cellpadding="5"
					cellspacing="0" class="tb_big">
					<tbody>
						<tr>
							<td><label><input name="sheji" type="checkbox" id="sheji" value="需要设计" disabled
								onclick="showCheck(this,'sjlx')"> 我要设计 </label><select name="sjlx"
								id="sjlx" style="display:none;">
									<option value="1">模板设计(简单)</option>
									<option value="2" selected="selected">来样设计(一般)</option>
									<option value="3">创意设计(复杂)</option>
							</select></td>
							<td><label><input name="zd" type="checkbox" disabled="" id="zd"
								onclick="return false" value="装订" checked=""> 装订(必选)</label></td>
							<td><label><input name="jiafengmian" type="checkbox" id="jiafengmian" value="加封面">
								加封面</label>&nbsp;<label><input name="yingfengmian" type="checkbox" id="yingfengmian" value="印封面"
								onclick="disCheck(this)"> 印封面</label></td>
							<td><label><input name="dhm" type="checkbox" id="dhm" value="打号码"> 打号码</label></td>
						</tr>
						<tr>
							<td><label><input name="zjld" type="checkbox" id="zjld" value="杂件联单"
								onclick="showCheck(this,'fengse')"> 杂件联单</label> <select name="fengse"
								id="fengse" style="display:none;">
									<option value="1色">2色</option>
									<option value="2色">3色</option>
									<option value="3色">4色</option>
									<option value="4色">5色</option>
									<option value="5色">6色</option>
									<option value="6色">7色</option>
									<option value="7色">8色</option>
							</select></td>
							<td><label><input name="jz" type="checkbox" id="jz" value="笔记本式胶装"
								onclick="showCheck(this,'jzlx')"> 胶装(笔记本式) </label><select name="jzlx"
								id="jzlx" style="display:none;">
									<option value="16开左右">16开左右</option>
									<option value="24开左右">24开左右</option>
									<option value="32开左右">32开左右</option>
							</select></td>
							<td><label><input name="yh" type="checkbox" id="yh" value="压痕压点线">
								压痕压点线</label></td>
							<td><label><input name="nrdb" type="checkbox" id="nrdb" value="内容到边"> 内容到边</label></td>
						</tr>
					</tbody>
				</table>
			</div>

		</form>

		<div class="page-contain">
			<table width="100%">
				<tr>
					<td align="center">&nbsp;</td>
					<td align="right" width="150"><a href="javascript:void(0);"
						onclick="javascript:submitCheck();" plain="true"
						iconCls="icon-add" class="easyui-linkbutton">自助报价</a></td>
				</tr>
			</table>
		</div>
		<div id="resultContent">
			
		</div>
	</div>
	<div id="pricelist" style="display: none;">
		<ul class="bjbt">
			<li id="iCity" style="display: none;"><select name="province"
				id="province"></select><select name="city" id="city"
				onchange="selectcity(this);"></select></li>
			<li><a href="javascript:void(0);" onclick="getPrice();"
				title="选择好上面的参数，马上为你实时报价">自助报价</a></li>
			<li id="loging"></li>
			<li id="pages"></li>
		</ul>
		<div id="nodata" style="display: none"></div>
		<table width="100%" border="0" cellpadding="0" cellspacing="0"
			id="showprice" style="display: none">
			<tbody>
				<tr>
					<td width="120" id="otherpid" style="display: none" valign="top"><div
							class="p1">
							<ul id="vids"></ul>
						</div></td>
					<td valign="top" class="myprice"><div id="GroupTabs"
							style="display: none">
							<ul class="Group" id="GroupList">
								<li><a onclick="GroupTab(this,0)" class="cur"><em><span>默认组</span></em></a></li>
							</ul>
							<div
								style="background: #deecfd; height: 2px; overflow: hidden; border-top: 1px solid #8db2e3;"></div>
						</div>
						<table width="100%" border="0" align="center" cellpadding="0"
							cellspacing="0" class="stable">
							<tbody>
								<tr align="center">
									<td colspan="3" rowspan="3"><span id="showx"><table
												width="100%" border="0" cellpadding="0" cellspacing="0"
												class="stable">
												<tbody>
													<tr align="center">
														<td width="18%"><strong>数量</strong></td>
														<td width="18%"><strong>单价（元）</strong></td>
														<td width="18%"><strong>总价（元）</strong></td>
													</tr>
													<tr align="center">
														<td class="thisprice" id="shuliang0">&nbsp;</td>
														<td class="thisprice" id="danjia0">&nbsp;</td>
														<td class="thisprice" id="sprice0">&nbsp;</td>
													</tr>
													<tr align="center">
														<td id="shuliang1">&nbsp;</td>
														<td id="danjia1">&nbsp;</td>
														<td id="sprice1">&nbsp;</td>
													</tr>
													<tr align="center">
														<td id="shuliang2">&nbsp;</td>
														<td id="danjia2">&nbsp;</td>
														<td id="sprice2">&nbsp;</td>
													</tr>
													<tr align="center">
														<td id="shuliang3">&nbsp;</td>
														<td id="danjia3">&nbsp;</td>
														<td id="sprice3">&nbsp;</td>
													</tr>
													<tr align="center">
														<td id="shuliang4">&nbsp;</td>
														<td id="danjia4">&nbsp;</td>
														<td id="sprice4">&nbsp;</td>
													</tr>
												</tbody>
											</table></span></td>
									<td width="50%" class="thisprice" id="company">&nbsp;</td>
								</tr>
								<tr align="center">
									<td class="thisprice" id="adtitle">&nbsp;</td>
								</tr>
								<tr align="center">
									<td><div id="ad2" class="ad2"></div></td>
								</tr>
								<tr>
									<td colspan="4"><table width="100%" border="0" cellpadding="0"
											cellspacing="0" class="stable" id="GroupTitle"
											style="display: none">
											<tbody>
												<tr>
													<td align="right" width="80">可送货区域：</td>
													<td id="adtitle3">sdf</td>
													<td align="right" width="70">强 项：</td>
													<td id="myitems">&nbsp;</td>
													<td style="display: none" align="right" width="70">质量宣言：</td>
													<td style="display: none" id="adtitle2">ddd</td>
												</tr>
												<tr>
													<td align="right">交货时间：</td>
													<td id="Deliverytime">&nbsp;</td>
													<td align="right">优惠活动1：</td>
													<td id="adtitle4">&nbsp;</td>
												</tr>
												<tr>
													<td align="right">结款方式：</td>
													<td id="adtitle5">&nbsp;</td>
													<td align="right">优惠活动2：</td>
													<td id="adtitle6">&nbsp;</td>
												</tr>
											</tbody>
										</table>
										<table width="100%" border="0" cellpadding="0" cellspacing="0"
											class="stable" id="CompanyTitle" style="display: none">
											<tbody>
												<tr>
													<td align="right" width="70">联系电话：</td>
													<td id="TEL">&nbsp;</td>
													<td align="right" width="70">联系人：</td>
													<td id="truename">&nbsp;</td>
												</tr>
												<tr>
													<td align="right">联系ＱＱ：</td>
													<td id="QQ">&nbsp;</td>
													<td align="right">地 址：</td>
													<td id="Address">&nbsp;</td>
												</tr>
											</tbody>
										</table> <span id="od"></span></td>
								</tr>
							</tbody>
						</table></td>
				</tr>
			</tbody>
		</table>
		<div id="ad6" style="display: none"></div>
	</div>

</body>