<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	//$('.bgloader').fadeOut(500);
});
</script>
<style type="text/css">
body {
	font-size: 12px;
}

.breadcrumb {
	padding: 8px 15px;
	list-style: none;
	background-color: #f5f5f5;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}

.breadcrumb li {
	text-align: -webkit-match-parent;
	line-height: 20px;
	display: inline-block;
	text-shadow: 0 1px 0 #ffffff;
}

.media,.media-body {
	margin: 10px 0 0;	
	line-height:20px;	
	overflow: hidden;
	zoom: 1;
}

.media-heading {
	margin: 0 0 5px;
}

.media-body a {
	display:inline-block;
	font-size: 18px;
	color: #0088cc;
	text-decoration: none;
}
.media-body a:hover {
	color: #0088cc;
	text-decoration: underline;
}
.media-body p{
	margin:10px 0;
}
.media-body .muted {
	color: #999999;
}
</style>
<include file="Include:toper" />
<div
	style="width: 90%; margin: 0 auto; padding-top: 20px; *zoom: 1; position: relative;">
	<div class="main_panel"
		style="width: 220px; position: absolute; left: 0; top: 20px; clear: both;">
		<div class="accordion-body">
			<div class="accordion-inner">
				<ul>
					<li class="header"><span>技术支持</span></li>
					<li>
						<div>
							<a href="<?=U('Support/question')?>">常见问题</a>
						</div>
					</li>
					<li>
						<div>
							<a href="<?=U('Support/information')?>">印刷知识</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="main_panel" style="margin-left: 240px; clear: both;">
		<ul class="breadcrumb">
			<li><i class="icon-home"></i><a href="#"> 技术支持</a>
			<span class="divider">/</span></li>
			<li><a href="<?=U('Support/information')?>">印刷知识</a>
			<span class="divider">/</span></li>
		</ul>
		<div class="accordion-body">
			<div class="accordion-inner" style="padding:0 15px;">
				<div class="media">
					<div class="media-body">
						<a style="color:" class="media-heading" title="使用YXcms需要收费么？"
							href="#" target="_blank"><h4>印刷品生产“完美”七个诀窍</h4></a>
						<p>　　世界上根本就不存在“完美”的印刷品，但是下面介绍的这七个窍门也许能帮人们获得近乎完美的印刷效果。 <br>　　1.如果你的印刷品采用了跨页的设计，那就意味着一个页面上的图像或文字会横跨到下一个书帖上，在这个时候，最好首先确定输纸导轨和叼纸牙在工厂里的位置，然后尽可能地把材料放置在离那个区域比较近的地方。</p>
						<p>　　此外，尽量不要把一个文字拆分到两个书帖上去印刷。</p>
						<p>　　2.始终保持1/16英寸（需要简单裁切的活件）或1/8英寸（其他活件）的出血。任何超过裁切线的图像，必须在裁切线外留出一定的余量（一般为3毫米），以便人们在修整裁切时对微量的对版不准进行校正，这个余量就叫出血。因此，在对一堆页面进行裁切的时候，适当地增加出血量能够提高整个活件的裁切质量。</p>
						<p>　　3.如果你发送出的印刷文件需要进行模切加工，那么最好把模切线储存在一个单独的图层里。这样一来，印刷厂就能在印刷之前把文件中的这个图层关掉。此外，如果你得到的样张已经被印刷上了模切线，那么就一定要让你的印刷厂知道这些线条是不需要印刷的。这听起来似乎很简单，但确实有很多人都做不到。</p>
						<p>　　4.首先要确定自己选择的纸张是否能够达到理想的印刷效果。有些纸可能太厚了，不能进行多次折页；有些纸可能不适合进行UV涂布，有些纸可能需要很多天才能彻底干燥，而有些纸则只能进行水性涂布，否则就会被装订设备损坏。</p>
						<p>　　5.在设计一个打算进行骑马订的多页文档时，一定要考虑到书刊内页或书刊在生产中发生移动、脱离书脊的情况，因为纸张页数越多，书脊厚度越高，就越容易出现这种情况。为避免由这种情况引起的内页文字和图像参差不齐的现象，最好从最外面的页面开始逐渐缩短每一个页面的装订线边距。</p>
						<p>　　6.当你为印刷厂提交一份印刷订单的时候，最好能附带一个印刷成品和书面说明。如果你的记录中没有标明产品的页数，那就要在你的样品上标注出来。把书面说明交给你的同事去阅读，让他们帮你找到其中不容易理解的地方。</p>
						<p>　　7.当你还处于构思阶段时，就应该跟装订厂取得联系，让他们知道你在想什么。他们不但能帮你实现自己的目标，而且还能为你提出很多节约成本的建议。</p>
						<p>　　如果你忽略这个步骤，那么很多原本可在高速设备上完成的简单工作可能就需要靠人们的手工操作来完成，这既会耽误生产时间，又会增加生产成本。此外，通过与装订厂的交流，你还能让更多的人了解和喜欢上你的作品。</p>
					</div>
				</div>
				<div class="media">
					<div class="media-body">
						<a style="color:" class="media-heading" title="使用YXcms需要收费么？"
							href="#" target="_blank"><h4>海德堡胶印机常见故障以及排除方法</h4></a>
						<p class="muted">2013-04-30 09:04:01&nbsp;&nbsp;&nbsp;&nbsp;点击:63</p>
						<p>　　故障一：纸张到达前规，整台机器停机</p>
<p>　　故障原因：1、此故障主要是纸未走好及光孔未调整好造成的。纸张到达前规时间过早或过晚。</p>
<p>　　 ★排除方法1：点动机器使纸张走到前规处，查看前规回程定位并下落至最低点时，纸张距前规距离是否为4～5mm。如未到5mm，则走纸过慢;反之则走纸过快。可松开操作面两个￠13mm螺母，借助法兰盘调至标准位置。</p>
<p>　　故障原因2：如纸未走到位，可能是前规处光控检测头动作有误。</p>
<p>　　★排除方法2：点动机器到前规上摆至定位处后，在前规处放上一张正方形纸，并轻轻推至靠住前规处，此时前规处光控检测头的两个光电显示灯应亮。如有一个不亮则说明有一边超前，造成未走到的假象，可顺时针旋转调节螺钉至显示灯亮，再转进1～2圈即可。</p>
<p>　　故障原因3：如若发现两个光电显示灯时亮时不亮或较暗，则可能是光眼上有纸毛等杂质遮住，致使光电检测出错。</p>
<p>　　★排除方法3：用柔软的布蘸酒精轻擦干净即可。</p>
<p>　　故障原因4：摆动牙开牙过小造成。可点动机器查看，当发现摆动牙下摆至快叼纸时把纸张弹回，则判断是摆动牙造成。</p>
<p>　　★排除方法4：点动机器至递纸牙到输纸台板上将叼纸的位置，此时可用90°直角规测牙垫与输纸板90°位置，用￠13mm套筒扳手套住牙轴歼牙螺母(操作面)，用1mm的螺片塞进牙齿上，再用3mm内六角扳手调整调节螺母，以拉出时的手感有少许阻力为准。</p>
<p>　　故障原因5：走纸歪斜或纸张毛边，造成停机。</p>
<p>　　★排除方法：此时可调节飞达及走纸杆，使两边快慢一致即可。</p>
<p>　　故障二：纸张侧规处拉不到位</p>
<p>　　故障原因1：由于二手机使用时间较长，特别是靠身拉规条磨损严重，造成拉规板顶住下台板而拉规球碰不到拉条。★排除方法：此时可松开拉规条上两个￠5mm的紧固螺母，将拉规条取下，用0.1mm的钢片(具体视磨损程度而定)做成与拉规条一致形状，并把它紧固在原拉条下面，加适量润滑油紧上即可，经使用效果良好。</p>
<p>　　故障原因2：拉规板起落靠山磨损严重，造成拉纸起落不干脆，也易引起走纸不到位。</p>
<p>　　★排除方法2：可拆下拉规板，并在原磨损靠山处加焊1mm厚度，并装于原位即可。</p>
<p>　　故障原因3：侧规拉簧压力过小。</p>
<p>　　★排除方法3：顺时针拧紧即可。</p>
<p>　　故障原因4：拉规球偏心调得过高。</p>
<p>　　★排除方法4：转动调至合适即可。</p>
<p>　　故障原因5：印刷白板纸时，4只毛刷轮压力过重。</p>
<p>　　★排除方法5：适当调轻或往后移至合适位置即可</p>
					</div>
				</div>
				<div class="media">
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>
<include file="Include:footer" />
</body>
</html>