<include file="Include:header" />
<script language="JavaScript" type="text/javascript">

</script>
</head>
<body style="background: none;">
	<div class="content">
		<form action="" method="post">
			<br />
			<p>
				<span class="label-notification">网站名称</span> <input id="phone"
					class="text-input small-input datepicker" type="text" name="phone" />
				*
			</p>
			<br />
			<p>
				<span class="label-notification">网站域名</span> <input id="domain"
					class="text-input small-input datepicker" type="text" name="domain" />
				*
			</p>
			<br />
			<p>
				<span class="label-notification">关键字</span>
				<textarea id="keys" class="text-input medium-input datepicker"
					type="text" name="keys"></textarea>
				*
			</p>
			<br />
			<p>
				<span class="label-notification">网站描述</span>
				<textarea id="desc" class="text-input medium-input datepicker"
					type="text" name="desc"></textarea>
				*
			</p>
			<br />
			<p>
				<span class="label-notification">网站备案号</span> <input id="icp"
					class="text-input small-input datepicker" type="text" name="icp" />
				*
			</p>
			<br />
			<div class="divline"></div>
			<br />
			<p>
				<span class="label-notification">关闭网站</span> <input type="radio"
					checked="" value="1" name="is_close_system"> 是 <input type="radio"
					value="0" name="is_close_system"> 否
			</p>
			<br />
			<p>
				<span class="label-notification">关闭原因</span>
				<textarea id="is_close_why"
					class="text-input medium-input datepicker" type="text"
					name="is_close_why"></textarea>
				*
			</p>
			<br />
			<div class="divline"></div>
			<br />
			<div class="clear"></div>
			<div class="bulk-actions">
				<input type="submit" class="button" value="保存修改" title="保存修改"
					style="margin-left: 150px;" />
			</div>
		</form>
	</div>
</body>
</html>