<include file="Include:header" />
<link href="__PUBLIC__/Jquey.DatePicker/ui.datepicker.css"
	rel="stylesheet" type="text/css" />
<script src="__PUBLIC__/Jquey.DatePicker/ui.datepicker.js"
	type="text/javascript"></script>
<script language="javascript">
$(document).ready(function(){
	$("#dstart").datepicker();
	$("#dend").datepicker();
});
function show(id){
	new Maya.Box({
		text : "订单详细信息",
		url : "<?=U ( "Report/showOrder" )?>/id/"+id,
		win : parent,
		width : 700,
		height : 220,
		btns : [
    		{
				text     : "    确定    ",
				isCancel : true	
			}
		]
	});
}

</script>

<div class="content">
	<div class="tag">筛选</div>
	<div class="tagc">
		<form id="form" method="get">
			<input type="hidden" name="s" id="s"
				value="/<?=MODULE_NAME?>/<?=ACTION_NAME?>/" />
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="100" height="30" align="right"><strong>日期范围：</strong></td>
					<td><input id="dstart" type="text" class="input_text" name="dstart"
						value="<?=$_GET['dstart'] == "" ? date ( "Y-m-d", strtotime ( "-30 day" ) ) : $_GET['dstart']?>" />
						— <input id="dend" class="input_text" type="text" name="dend"
						value="<?=$_GET['dend'] == "" ? date ( "Y-m-d") : $_GET['dend']?>" />&nbsp;&nbsp;&nbsp;
						<a href="#" class="easyui-linkbutton"
						onclick="javascript:$('#form').submit();" iconCls="icon-search">搜索</a></td>
				</tr>
			</table>
		</form>
	</div>
	<div class="tag">我的订单列表</div>
	<div class="tagc" style="margin-bottom: 0; padding: 1px;">
		<table width="100%" border="0" cellspacing="0" cellpadding="0"
			class="tb tblGrid">
			<thead>
				<tr bgcolor="#CCCCCC">
					<!-- 会员号 用户名 所在组 公司名称 地区 联系人 QQ 登录/报价  -->
					<th width="30" align="center"></th>
					<th align="left" width="120"><strong>编号</strong></th>
					<th align="left" width="30"><strong>项目数</strong></th>
					<th align="left" width="120"><strong>订单金额</strong></th>
					<th align="center" width="60"><strong>日期</strong></th>
					<th align="left" width="50"><strong>状态</strong></th>
					<th align="left" width="120"><strong>备注</strong></th>
					<th align="left" width="30"><strong>详细</strong></th>
				</tr>
			</thead>
			<tbody>
			<?php
			$i = 0;
			foreach ( $orderArr as $row ) :
				$i ++;
				// $bg = $i % 2 == 0 ? 'bgcolor="#FAFAFA"' : "";
				?>
				<tr>
					<td align="center"><?=$i?></td>
					<td align="left"><?= $row['o_number'] ?></td>
					<td align="left"><?= $row['total'] ?></td>
					<td align="center">￥<?=$row['o_price']?></td>
					<td align="left"><?=$row ['o_date']?></td>
					<td align="left"><?php
				// 1.等待确认。2.审核中。3.生产中。4.生产完成，等待送货。5.送货中。6.已完成。
				if ($row ['o_isDelete']) {
					echo '<span style="color:#dedede;">已取消<span>';
				} else {
					switch ($row ['o_status']) {
						case '1' :
							echo '<span style="color:#C3A900;">等待确认<span>';
							break;
						case '2' :
							echo '审核中。';
							break;
						case '3' :
							echo '生产中。';
							break;
						case '4' :
							echo '生产完成，等待送货。';
							break;
						case '5' :
							echo '送货中。';
							break;
						case '6' :
							echo '<span style="color:#438787;">成交<span>';
							break;
					}
				}
				?></td>
					<td align="left"><?= $row['o_desc'] ?></td>
					<td align="left"><a href="#" class="easyui-linkbutton"
						onclick="show(<?=$row['id']?>);" plain="true"
						iconCls="icon-search">详细</a></td>
				</tr>
			<?php endforeach; ?>
        </tbody>
		</table>
		<!-- 分页文字 -->
		<div class="page-contain">
			<table width="100%">
				<tr>
					<td align="center" width="200">
						<!-- <input type="submit"
						class="maya_btn export_btn" value="导出Excel" /> <input
						type="submit" class="maya_btn import_btn" value="导入Excel" /> -->
					</td>
					<td align="right"><?=$page->printCount();$page->pageNormal();$page->printDropMenu();?></td>
				</tr>
			</table>
		</div>
	</div>
</div>
</body>
</html>