<include file="Include:header" />
<script language="JavaScript" type="text/javascript">
function $(){return document.getElementById?document.getElementById(arguments[0]):eval(arguments[0]);}
function getvalue(ii){
		if (ii==1){$("linjia").value="";}else if (ii==2){$("dunjia").value="";}
		getprice($("chichun").value,$("kezhong").value,$("dunjia").value,$("linjia").value);
	
}
function getprice(chichun,kezhong,dunjia,linjia){	
	var w,h,wh = $("chichun").value
	if (wh!=""){
		wh = wh.split('*');
		w = wh[0];h = wh[1];
	}

	if(kezhong=="" || isNaN(kezhong)){return;}
	if(dunjia=="" || isNaN(dunjia)){dunjia=0;}
	if(linjia=="" || isNaN(linjia)){linjia=0;}
	var zhizhong,zhijia,dianjia,linzhong,linshu	
	
	if (dunjia>0)  {
		//吨转令
		zhizhong=kezhong*w*h/1000/1000;					//纸重(单位:克)
		zhijia=dunjia/1000/1000;						//一克纸价格
		linzhong=zhizhong*500/1000;						//标准令重		
		linshu=1000/linzhong;							//折算令数
		dianjia=zhizhong*zhijia;						//纸张单价
		linjia=dianjia*500 ;							//纸张令价
		$("mydunjia").innerHTML=dunjia+"元/吨";
		$("mydunjia").className="";
		$("mylinjia").innerHTML=linjia.toFixed(3)+"元/令";
		$("mylinjia").className="thisprice";
		
	}else if (linjia>0)  {
		//令转吨
		zhizhong=kezhong*w*h/1000/1000;					//纸重(单位:克)
		linzhong=zhizhong*500/1000;						//标准令重		
		linshu=1000/linzhong;							//折算令数
		dianjia=linjia/500;								//纸张单价
		dunjia=dianjia/zhizhong*1000*1000 ;				//纸张令价
		$("mylinjia").innerHTML=linjia+"元/令";
		$("mylinjia").className="";
		$("mydunjia").innerHTML=dunjia.toFixed(0)+"元/吨";
		$("mydunjia").className="thisprice";
	}else{return;}

	
	$("mychichun").innerHTML=w+"×"+h;
	$("mykezhong").innerHTML=kezhong;

	$("mydianjia").innerHTML=dianjia.toFixed(3)+"元/张";
	$("mylinzhong").innerHTML=linzhong.toFixed(3)+"千克/令";
	$("mylinshu").innerHTML=linshu.toFixed(3)+"令/吨";
	
}
document.oncontextmenu=function(){return false;}
document.onselectstart=function(){return false;}
</script>
</head>

<body style="background: none;">
	<div class="content">
		<div class="body_title">
			<h1>
				纸价吨令转换 <em>大度正度纸价转换、吨转令、令转吨</em>
			</h1>
		</div>
		<table width="670" border="0" cellpadding="0" cellspacing="0" class="tb">
			<tbody>
				<tr>
					<th>纸张尺寸</th>
					<th>克重</th>
					<th>吨价</th>
					<th>令价</th>
				</tr>
				<tr align="center">
					<td><select name="chichun" id="chichun" style="margin-right: 30px;"
						onchange="getvalue()">
							<option value="889*1194">889*1194(大度)</option>
							<option value="787*1092">787*1092(正度)</option>
							<option value="850*1198">850*1188</option>
							<option value="880*1230">880*1230</option>
							<option value="890*1240">890*1240</option>
							<option value="900*1280">900*1280</option>
							<option value="1000*1400">1000*1400</option>
							<option value="787*1140">787*1140</option>
							<option value="787*960">787*960</option>
							<option value="890*1280">890*1280</option>
							<option value="800*1100">800*1100</option>
					</select></td>
					<td><div style="position: relative; width: 64px;">
							<span style="overflow: hidden;"> <select style="width: 64px;"
								onchange="$('kezhong').value=this.value;getvalue();">
									<option value="35">35</option>
									<option value="40">40</option>
									<option value="45">45</option>
									<option value="49">49</option>
									<option value="50">50</option>
									<option value="52">52</option>
									<option value="55">55</option>
									<option value="60">60</option>
									<option value="65">65</option>
									<option value="70">70</option>
									<option value="75">75</option>
									<option value="80">80</option>
									<option value="85">85</option>
									<option value="90">90</option>
									<option value="100">100</option>
									<option value="105">105</option>
									<option value="120">120</option>
									<option value="128">128</option>
									<option value="130">130</option>
									<option value="140">140</option>
									<option value="150">150</option>
									<option value="157" selected="selected">157</option>
									<option value="160">160</option>
									<option value="170">170</option>
									<option value="180">180</option>
									<option value="190">190</option>
									<option value="200">200</option>
									<option value="210">210</option>
									<option value="220">220</option>
									<option value="230">230</option>
									<option value="240">240</option>
									<option value="250">250</option>
									<option value="300">300</option>
									<option value="350">350</option>
									<option value="400">400</option>
							</select>
							</span>


							<div
								style="z-index: 10; position: absolute; width: 42px; height: 20px; left: 3px; top: 1px;">
								<iframe
									style="position: absolute; z-index: -1; width: 37px; height: 16px; left: 1px; top: 1px; scrolling: no;"
									frameborder="0"></iframe>
								<input name="kezhong" id="kezhong"
									style="width: 37px; height: 16px; border: 0;" value="157"
									size="4" maxlength="4" onkeyup="getvalue()">
							</div>
						</div></td>
					<td><input type="text" name="dunjia" id="dunjia" size="8"
						maxlength="7" style="margin-right: 30px;" onkeyup="getvalue(1)"
						title="输入吨价转令价"></td>
					<td><input type="text" name="linjia" id="linjia" size="8"
						maxlength="7" style="margin-right: 30px;" onkeyup="getvalue(2)"
						title="输入令价转吨价"></td>
				</tr>
			</tbody>
		</table>
		<br>
		<table width="670" border="0" cellpadding="0" cellspacing="0"
			class="tb">
			<tbody>
				<tr>
					<th>纸张尺寸</th>
					<th>克重</th>
					<th>令重</th>
					<th>令数</th>
					<th>吨价</th>
					<th>令价</th>
					<th>单价</th>
				</tr>
				<tr align="center">
					<td id="mychichun">&nbsp;</td>
					<td id="mykezhong">&nbsp;</td>
					<td id="mylinzhong">&nbsp;</td>
					<td id="mylinshu">&nbsp;</td>
					<td id="mydunjia">&nbsp;</td>
					<td id="mylinjia">&nbsp;</td>
					<td id="mydianjia">&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</div>
</body>
<style type="text/css"></style>
</html>