<include file="Include:header" />
<script language="javascript">
var oPage = {pageIndex:1,pageSize:10};
$(document).ready(function(){
	//$(".chosen").chosen();
	$('#btnedit').linkbutton('disable');
	$('#btndel').linkbutton('disable');	
	$('#btnUnsel').linkbutton('disable');
	initDataGrid("tbl","通用印刷机列表","<?=U('Machine/getAllMC4Json')?>","#dbTool");
	
});

function getSelected(num){
	var selected = $('#tbl').datagrid('getSelections');
	//console.info(selected[0].name);
	if(num != undefined){
		if(selected.length == 0){
			parent.Maya.Msg("请选择操作项【单击行即可】");
			return "";
		}
		if(selected.length > num){
			parent.Maya.Msg("所选数量超出操作限制。");
			return "";
		}
	}
	var id = "";
	for(var i = 0 ; i < selected.length;i++){
		id += selected[i].id;
		id += i+1 == selected.length ? "" : ","
	}
	return id;
}

function submitForm(type){
	var id = 0;
	var title = "添加";
	if(type == "edit"){
		var id = getSelected(1);
		if(!id){
			return;
		}
		title = "修改";
	}
	new Maya.Box({
		text : "通用印刷机"+title,
		url : "<?=U ( "Machine/actionCheckIndex" )?>/type/"+type+"/id/"+id,
		win : parent,
		width : 600,
		height : 220,
		btns : [
    		{
				text : "    确定    ",
				onClick : function(w){
					w.getIframe().submitForm(w);
					// _self.close();
				}	
			},
			{
				text : "    取消    ",
				onClick : function(w){
    				w.close();
				}	
			}
		]
	});
}

function  del(){
	var selected = $('#tbl').datagrid('getSelections');
	//var id = getSelected();
	//if(!id){
	//	return;
	//}
	var id = "";
	var title = "";
	for(var i = 0 ; i < selected.length;i++){
		title += "<b>"+(i+1)+".</b>"+selected[i].m_name;
		title += i+1 == selected.length ? "" : ";&nbsp;&nbsp;&nbsp;";
		title += (i+1)%3 == 0 ? "<br />" : "";
		id += selected[i].id;
		id += i+1 == selected.length ? "" : ",";
	}
	new Maya.Box({
		text : "删除记录",
		chtml : "<b>确定要删除以下通用打印机信息？</b><br />"+title+"",
		win : parent,
		isAlert : true,
		iframeAuto : false,
		overlayAlpha : .5,
		iframeScroll : "auto",
		inlineAuto : false,
		type : "inline",
		btns : [
			{
				text : "确定"	,
				onClick : function(w){
					$.post(
							"<?=U("Machine/actionCheckIndex")?>",
							{
								type:'del',
								id:id
							},
							function(data){
								if(data.status=="1"){
									parent.Maya.Msg({
										type : "success",
										msg : "操作成功",
										call : function(){
											w.close();
											freshIframe();
										}
									});	
								}else{
									parent.Maya.Msg({
				                       type : "fail",
				                       msg : data.info
				               		});
								}
							},
							"json"
						);
  	       		 }
			},
			{
				text : "取消"	,
				isCancel : true
			}
		]
	});	
}
function formatStatus(val,row){
	if (val == 0){  
        return '<a href="#" title="停用" iconCls="icon-no" plain="true"><img src="__PUBLIC__/images/center/icons/cross_circle.png" /></a>';  //
    } else {  
        return '<a href="#" title="启用" iconCls="icon-no" plain="true"><img src="__PUBLIC__/images/center/icons/tick_circle.png" /></a>';    
    }  
}
</script>
<div id="dbTool">
		<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="submitForm('add')">添加</a>
		<a href="#" id="btnedit" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="submitForm('edit')">修改</a>
		<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-cancel" plain="true"  onclick="del()">删除</a>|
		<!-- <a href="#" class="easyui-linkbutton" iconCls="icon-outdepot" plain="true" >导出</a> 
		<a href="#" id="btndel" class="easyui-linkbutton" iconCls="icon-perf" plain="true" onclick="updateAttr()">规格设置</a>-->
		<a href="#" id="btnUnsel" class="easyui-linkbutton" iconCls="icon-back" plain="true"  onclick="$('#tbl').datagrid('clearSelections')">取消选中</a>
		<span style="color: #FF0000; margin-left: 30px;">提示：单击行即可选中(或取消)。</span>
</div>
<div class="content">
	<table id="tbl">
		<thead>
			<tr>
				<th field="m_type" width="80" align="left"><strong>类型</strong></th>
				<th field="m_name" width="150" align="center"><strong>机器名</strong></th>
				<th field="m_color" width="80" align="center"><strong>颜色</strong></th>
				<!-- <th field="m_maxLength" width="80" align="center"><strong>最大印刷尺寸</strong></th>
				<th field="m_maxThick" width="80" align="center"><strong>印刷厚度</strong></th> -->
				<th field="m_price" width="60" align="center"><strong>起印费</strong></th>
				<th field="m_versionCost" width="60" align="center"><strong>版费</strong></th>
				<th field="m_lastDate" width="150" align="center"><strong>更新时间</strong></th>
				<th field="m_status" width="40" align="center" formatter="formatStatus"><strong>状态</strong></th>
				<th field="m_desc" width="150" align="left"><strong>备注</strong></th>
			</tr>
		</thead>
	</table>
</div>
</body>
</html>