<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo C('MYCOMPANY')."-".C('SYSNAME');?></title>
<style type="text/css">
boyd,input,div,select,form,ul,li,textarea {
	font-family: "微软雅黑";
	font-size: 12px;
	color: #333;
	margin: 0px;
	padding: 0px;
	outline: none;
}

a {
	text-decoration: none;
	color: #dedede;
	cursor: pointer;
}

a:hover {
	text-decoration: none;
	color: #ffffff;
}

.login_input {
	font-family: "微软雅黑";
	font-size: 14px;
	line-height: 37px;
	border: 1px solid #999;
	-webkit-transition: box-shadow 0.3s linear;
	-moz-transition: box-shadow 0.3s linear;
	-ms-transition: box-shadow 0.3s linear;
	-o-transition: box-shadow 0.3s linear;
	transition: box-shadow 0.3s linear;
	height: 37px;
	width: 190px;
	padding-left: 10px;
	display: inline-block;
	box-shadow: inset 0px 0px 8px 1px rgba(0, 0, 0, .1);
	color: #999;
}

.login_input:focus {
	border: 1px solid #35840a;
	color: green;
	box-shadow: inset 0px 0px 8px 1px rgba(0, 0, 0, .1), 0px 0px 8px 1px
		rgba(53, 132, 10, .3);
}

.login_btn {
	background-image: url(__PUBLIC__/images/login/login_btn.png);
	background-repeat: no-repeat;
	background-position: left -39px;
	height: 39px;
	width: 102px;
	position: relative;
	top: 14px;
	*top: 0px;
	top: 13px\0;
	display: inline-block;
}

.login_btn:hover {
	background-position: left -0px;
}

.login_btn:active {
	background-position: left -78px;
}

.a_grid_u {
	color: #35890a;
	text-decoration: underline;
}
</style>
<link href="__PUBLIC__/mayamsg/mayamsg.css" rel="stylesheet"
	type="text/css" />
<script src="__PUBLIC__/mayamsg/mayamsg.js" type="text/javascript"></script>
<script src="__PUBLIC__/js/jquery.min.js" type="text/javascript"></script>
<script src="__PUBLIC__/js/jquery.form.js" type="text/javascript"></script>
<script>
function submitForm(){
	  Maya.Msg({
		    msg : "正在登录中，请稍后....",
		    sec : 5
	  });
        $.post(
                "<?=U("Login/loginCheck")?>",
                $("#loginForm").formSerialize(),
                function(data){
                        if(data.status=="success"){
                                Maya.Msg({
                                        type : "success",
                                        msg : "登录成功，正在跳转中....",
                                        sec : 1.5,
                                        call : function(){
                                                window.location="<?=U("Index/index")?>";
                                        }
                                });
                        }else{
                                Maya.Msg({
                                        type : "fail",
                                        msg : data.msg
                                });
                        }
                },
                "json"
        );
}
function checkForm(){
	//用户名
        if(_("login_name").value=="" || _("login_name").value=="登录名"){
                Maya.Msg({
                        msg : "请输入<strong>登录名</strong>"
                });
		return;
	}
        //密码
	if(_("login_pwd").value=="" || _("login_pwd").value=="登录密码"){
                Maya.Msg({
                        msg : "请输入<strong>登录密码</strong>"
                });
		return;
	}
	submitForm();
}
Maya.BindEvent(window,"load",function(){
	//按钮提交
        Maya.BindEvent(_("login_btn"),"click",function(){
		checkForm();	
	});
        //回车提交
        Maya.BindEvent(document.body,"keydown",function(e){
                //如果是回车键
                var e=event || e;
                if(e.keyCode==13){
                        checkForm();
                }
        });
        //自动填写
        <?php if($_COOKIE['wxpsi_name']!=""):?>
        $("#login_name").attr("value","<?=$_COOKIE['wxpsi_name']?>");
        //if(!Maya.isIE6()){("login_pwd").type="password";}
        $("#login_pwd").attr("value","<?=$_COOKIE['wxpsi_pwd']?>");
        <?php endif;?>
        /*<?php if(!isset($_COOKIE['notishi'])):?>
	//检测浏览器
	if(Maya.isIE6()){
		new Maya.Box({
			isAlert : true,
			type : "inline",
			effect : true,
			width : 600,
			btnClose : false,
			chtml : "<strong>注意</strong>：系统检测到您的浏览器是<span style='color:red;font-weight:bold;'>IE6</span>系列浏览器，请安装系统提供的“谷歌浏览器”",
			btns : [
				{
					text : "安装 google浏览器",
					onClick : function(w){
						window.location="Public/download/22.0.1229.92_chrome_installer.exe";
					}
				},
				{
					text : "暂时不想安装",
					isCancel : true
				},
                                {
                                        text : "不要再提示我安装谷歌浏览器",
                                        onClick : function(w,o,e){
                                                o.disabled=true;
                                                $.get(
                                                        "<?=U("Index/NoTiShi")?>",
                                                        function(data){
                                                                if(data.status=="success"){
                                                                        w.close();
                                                                }else{
                                                                        
                                                                }
                                                        },
                                                        "json"        
                                                )
                                        }
                                }
			]
		});
	}
        <?php endif;?>*/
});
</script>
</head>

<body scroll="no"
	style="background: url(__PUBLIC__/images/login/bg.jpg) repeat;">
	<div
		style="margin-top: 370px; height: 33px; text-align: right; color: #fff; border-bottom: 1px #025C57 solid; overflow: hidden;">
		<div style="float: right; width: 400px;">
			<include file="Include:footer" />
		</div>
		<div style="clear: both;"></div>
	</div>
	<div style="text-align: center; border-top: 1px #039B93 solid;">
		<div
			style="_height: 10px; *height: 10px; _font: 0px Arial; background: none; _margin-bottom: 10px;"></div>
		<form id="loginForm" style="height: 55px;">
			<input name="login_name" type="text" class="login_input"
				id="login_name" onfocus="if(this.value=='登录名'){this.value='';}"
				onblur="if(this.value==''){this.value='登录名';}" value="登录名" /> <input
				name="login_pwd" type="password" class="login_input" id="login_pwd"
				onfocus="if(this.value=='登录密码'){this.value='';}"
				onblur="if(this.value==''){this.value='登录密码登录密码登录密码登录密码';}"
				value="登录密码" /> <span class="login_btn" id="login_btn"></span>
		</form>
	</div>
	<div
		style="position: absolute; top: 200px; left: 50%; margin-left: -470px; height: 100px; width: 650px; text-align: center; color: #666; background: url(__PUBLIC__/images/login_logo.png) 15px 5px no-repeat;">
	</div>
</body>
</html>
