<include file="Include:header" />
<script language="javascript">
$(document).ready(function(){
	//$('.bgloader').fadeOut(500);
});
</script>
<style type="text/css">
body {
	font-size: 12px;
}

.breadcrumb {
	padding: 8px 15px;
	list-style: none;
	background-color: #f5f5f5;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}

.breadcrumb li {
	text-align: -webkit-match-parent;
	line-height: 20px;
	display: inline-block;
	text-shadow: 0 1px 0 #ffffff;
}

.media,.media-body {
	margin: 10px 0 0;	
	line-height:20px;	
	overflow: hidden;
	zoom: 1;
}

.media-heading {
	margin: 0 0 5px;
}

.media-body a {
	display:inline-block;
	font-size: 18px;
	color: #0088cc;
	text-decoration: none;
}
.media-body a:hover {
	color: #0088cc;
	text-decoration: underline;
}

.media-body .muted {
	color: #999999;
}
</style>
<include file="Include:toper" />
<div
	style="width: 90%; margin: 0 auto; padding-top: 20px; *zoom: 1; position: relative;">
	<div class="main_panel"
		style="width: 220px; position: absolute; left: 0; top: 20px; clear: both;">
		<div class="accordion-body">
			<div class="accordion-inner">
				<ul>
					<li class="header"><span>技术支持</span></li>
					<li>
						<div>
							<a href="<?=U('Support/question')?>">常见问题</a>
						</div>
					</li>
					<li>
						<div>
							<a href="<?=U('Support/information')?>">印刷知识</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="main_panel" style="margin-left: 240px; clear: both;">
		<ul class="breadcrumb">
			<li><i class="icon-home"></i><a href="#"> 技术支持</a>
			<span class="divider">/</span></li>
			<li><a href="<?=U('Support/question')?>">常见问题 Q&A</a>
			<span class="divider">/</span></li>
		</ul>
		<div class="accordion-body">
			<div class="accordion-inner" style="padding:0 15px;">
				<div class="media">
					<div class="media-body">
						<a style="color:" class="media-heading" title="使用YXcms需要收费么？"
							href="#" target="_blank"><h4>7788印刷报价软件有哪些优点？</h4></a>
						<p class="muted">&nbsp;</p>
						<p>我公司开发的“7788印刷报价软件”正因“精、准、简”从而深受客户喜爱。因为专业，所以卓越。</p>
							<p>所谓“精”………………报价精准度误差控制在1%范围以内</p>
							<p>所谓“准”………………单据打印、财务、仓储模块能够做到准确无误，无一漏单</p>
							<p>所谓“简”………………客户使用简单，生产厂家易于后台的管理与操作</p>
							<p>选择“7788印刷报价软件”，您的选择是睿智的！</p>
					</div>
				</div>
				<div class="media">
					<div class="media-body">
						<a style="color:" class="media-heading" title="使用YXcms需要收费么？"
							href="#" target="_blank"><h4>7788印刷报价软件，能为您做些什么？</h4></a>
							<p>&nbsp;</p>
							<p>1.自助报价…………………………………………不用双手、不打电话也可为客户报价</p>
							<p>2.在线订单系统……………………………………全自动化办公，减轻您的负担</p>
							<p>3.单据打印系统……………………………………全自动模式生成相关单据打印功能</p>
							<p>4.财务模块…………………………………………充值、做帐、收款等等再也不是问题<</p>
							<p>5.仓储模块…………………………………………进销存，无需专业人员也可轻松搞定</p>
							<p>6.公司网站建设……………………………………实现自动化、简单化、市场化转型</p>
							<p>7.定制其他个性应用…………………………… 可根据客户需求定做其他应用程序</p>
					</div>
				</div>
				<div class="media">
					<div class="media-body">
						<a style="color:" class="media-heading" title="使用YXcms需要收费么？"
							href="#" target="_blank"><h4>7788印刷报价软件，适用范围？</h4></a>
						<p>&nbsp;</p>
							<p>1.印刷生产厂家</p>
							<p>2.印刷中介</p>
							<p>3.图文店</p>
							<p>4.个人</p>
					</div>
				</div>
				<div class="media">
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>
<include file="Include:footer" />
</body>
</html>