<include file="Include:header" />
<link href="__PUBLIC__/Plugin/slider/css/slider.css" rel="stylesheet"
	type="text/css" />
<script type="text/javascript"
	src="__PUBLIC__/Plugin/slider/js/slider.js"></script>
<script type="text/javascript">
<!--
jQuery(document).ready(function($)
{
	/**/$('.flexslider').flexslider({
        animation: "slide",
        slideshow: true,                //Boolean: Animate slider automatically
        slideshowSpeed: 4000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
        animationSpeed: 600
      });
});
//-->
</script>
<include file="Include:toper" />
<div class="navigator">
	<div class="slider" style="padding: 0 10px;height: 430px;">
		<!--  background: url(__PUBLIC__/Plugin/slider/images/ad_home.jpg);  --><div class="flexslider">
			<ul class="slides">
				<li>
					<div class="img">
						<img src="__PUBLIC__/Plugin/slider/images/slide_1.jpg" alt="" />
					</div>
				</li>
				<li>
					<div class="img">
						<img src="__PUBLIC__/Plugin/slider/images/slide_2.jpg" alt="" />
					</div>
				</li>
				<li>
					<div class="img">
						<img src="__PUBLIC__/Plugin/slider/images/slide_3.jpg" alt="" />
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="navigator">
	<div class="main_content">
		<div style="width: 880px; overflow: hidden; margin: 0 auto;">
			<!-- <div class="main_panel" style="width: 300px; float: left;">
				<div class="accordion-heading">
					<a class="accordion-toggle" data-toggle="collapse"
						data-parent="#accordion2" href="#collapse12"> <i class="icon-edit"></i>
						标题
					</a>
				</div>
				<div class="accordion-body">
					<div class="accordion-inner">
						<p></p>
					</div>
				</div>
			</div>
			<div class="main_panel index_panel">
				<div class="accordion-body">
					<div class="accordion-inner">
						<img src="__PUBLIC__/Plugin/slider/images/ad_auto.jpg" alt="" />
						<span class="span">简单</span>
					</div>
				</div>
			</div>
			<div class="main_panel index_panel">
				<div class="accordion-body">
					<div class="accordion-inner">
						<img src="__PUBLIC__/Plugin/slider/images/ad_auto.jpg" alt="" />
						<span class="span">实用</span>
					</div>
				</div>
			</div>
			<div class="main_panel index_panel" style=" margin: 0;">
				<div class="accordion-body">
					<div class="accordion-inner">
						<img src="__PUBLIC__/Plugin/slider/images/ad_auto.jpg" alt="" />
						<span class="span">高效</span>
					</div>
				</div>
			</div> -->
		</div>
		<div class="clear"></div>
	</div>
</div>
<div id="bottom">
	<div id="down">
		<a onfocus="this.blur()" href="#" target="_self"> 下载试用 </a>
	</div>
	<div id="mail">
		<div>
			<p>QQ：2490477760</p>
			<p>
				技术支持：<a href="mailto:support@7788ysw.com">support@7788ysw.com</a>
			</p>
		</div>
	</div>
	<div id="contact" style="float: right;">
		<a onfocus="this.blur()" href="#" target="_self"> 在线留言 </a>
	</div>
	<div class="clear"></div>
</div>
<include file="Include:footer" />